// Modelos de fábrica são código; as apresentações criadas ficam somente na biblioteca.
const item=(title,text,extra={})=>({title,text,...extra});
const route='flowchart LR\n  A([Pedido]):::hi --> B{Dados válidos?}\n  B -->|sim| C[Executar tarefa]\n  B -.->|não| D[Informar erro]:::vazado\n  C ==> E[Guardar resultado]:::em';
export const DEMO_NAMES={lavanda:'Estúdio lavanda',executivo:'Relatório executivo',workshop:'Workshop visual',compacto:'Demo — material de consulta',diagramas:'Demo — diagramas vivos'};
export function demoDeck(kind) {
  if(!DEMO_NAMES[kind])throw Error('Modelo não encontrado.');
  const common={title:DEMO_NAMES[kind],theme:kind==='lavanda'?'bauhaus':kind==='executivo'?'prata':kind==='workshop'?'sinal':'editorial',palette:kind==='executivo'?'corporativo':'lavanda',duration:15,maxWords:140};
  const cover={layout:'cover',title:DEMO_NAMES[kind],subtitle:'Um modelo para adaptar ao seu conteúdo',kicker:'SAGADECK · MODELOS',tone:'dark'};
  const end={layout:'end',title:'O próximo passo\ncomeça aqui.',subtitle:'Duplique este modelo na biblioteca e adapte os textos.'};
  const items=[item('Descobrir','Comece pela pergunta certa.',{icon:'search'}),item('Experimentar','Teste uma hipótese com dados.',{icon:'flask-conical'}),item('Construir','Transforme o aprendizado em produto.',{icon:'blocks'}),item('Observar','Acompanhe o uso e os resultados.',{icon:'chart-column'}),item('Evoluir','Use o que aprendeu para melhorar.',{icon:'sparkles'})];
  let slides;
  if(kind==='lavanda')slides=[cover,{layout:'mosaic',title:'Cinco ideias, uma composição.',items},{layout:'ribbon',title:'Um caminho em três momentos.',items:items.slice(0,3),tone:'accent'},{layout:'quote',quote:'Uma boa apresentação deixa a ideia respirar.',by:'Princípio deste modelo',tone:'dark'},{layout:'mosaic',title:'A grade cresce com o conteúdo.',items:[...items,...items.slice(0,3)].map((x,i)=>({...x,title:`${i+1}. ${x.title}`}))},end];
  if(kind==='executivo')slides=[{...cover,subtitle:'Decisões claras, números contextualizados.'},{layout:'mosaic',title:'O que precisa de uma decisão.',items:[item('Prioridade','Melhorar o atendimento nos canais digitais.',{value:'01'}),item('Investimento','Validar o piloto antes de expandir.',{value:'02'}),item('Próximo marco','Apresentar resultados em quatro semanas.',{value:'03'})]},{layout:'stats',title:'O piloto em números',stats:[{value:'24',label:'participantes'},{value:'4',label:'semanas'},{value:'3',label:'hipóteses'}],source:'Dados fictícios para demonstrar o modelo.'},{layout:'ribbon',title:'Plano de trabalho',items:items.slice(0,4)},{layout:'compare',title:'A decisão em perspectiva',left:{title:'Continuar como está',text:'Sem custo de mudança; os problemas atuais permanecem.'},right:{title:'Testar em pequena escala',text:'Aprendizado limitado, com critérios de sucesso definidos.',hl:true}},end];
  if(kind==='workshop')slides=[{...cover,subtitle:'Aprender, experimentar, explicar.'},{layout:'question',question:'O que acontece depois do pedido?',options:['A resposta vem na hora','Recebemos um identificador','Depende do modo'],hint:'Escolha antes de avançar.'},{layout:'diagram',title:'Do pedido ao resultado',mermaid:route},{layout:'codewalk',title:'Uma chamada, três observações',language:'javascript',code:'const response = await fetch(url);\nif (!response.ok) throw new Error(response.status);\nconst dados = await response.json();\nconsole.log(dados);',steps:[{title:'Pedido',text:'A execução aguarda a resposta HTTP.',highlight:[1]},{title:'Validação',text:'Um erro HTTP interrompe o fluxo.',highlight:[2]},{title:'Resultado',text:'O JSON vira um objeto.',highlight:[3,4]}]},{layout:'dossier',title:'Para consultar depois',items:[item('URL','Identifica o recurso. Evite colocar segredos no endereço.'),item('Status','Indica o resultado HTTP. Um 200 não substitui validar o conteúdo.'),item('Corpo','Carrega os dados do pedido ou da resposta.'),item('Timeout','Limita quanto tempo a aplicação espera.')]},end];
  if(kind==='compacto') {
    const code=['import time','import requests','','def acompanhar(base, pedido, timeout=60):','    inicio = requests.post(','        f"{base}/tarefas", json=pedido, timeout=10','    )','    inicio.raise_for_status()','    tarefa = inicio.json()["id"]','    limite = time.monotonic() + timeout','','    while time.monotonic() < limite:','        resposta = requests.get(','            f"{base}/tarefas/{tarefa}", timeout=10','        )','        resposta.raise_for_status()','        dados = resposta.json()','        status = dados["status"]','','        if status == "finished":','            return dados["resultado"]','        if status == "failed":','            raise RuntimeError(dados["erro"])','','        time.sleep(1)','','    raise TimeoutError("A tarefa não terminou")'].join('\n');
    slides=[{...cover,subtitle:'Código, payloads e instruções no mesmo material.'},{layout:'code',title:'No palco: explique a ideia.',language:'python',code:'resposta = iniciar(pedido)\nid = resposta["id"]\n\nwhile not terminou(id):\n    esperar(1)\n\nmostrar(resultado(id))',notes:'Versão conceitual para explicar ao público; não é código executável.'},{layout:'code',title:'Na consulta: o exemplo completo.',density:'dense',language:'python',code,source:'API fictícia. Ajuste as rotas e instale requests. 27 linhas sem ocultar o final.'},{layout:'dossier',title:'Como ler a resposta',items:[item('Identificador','Guarde o id devolvido ao iniciar. Ele é usado nas consultas seguintes.',{code:'{"id":"tarefa-42","status":"started"}'}),item('Enquanto executa','Consulte com um intervalo definido e limite total de espera.',{code:'{"id":"tarefa-42","status":"running"}'}),item('Ao finalizar','Valide o status antes de ler o resultado de cada etapa.',{code:'{"status":"finished",\n "resultado":[\n  {"etapa":"ocr","paginas":12},\n  {"etapa":"resumo","texto":"…"}\n ]}'}),item('Se falhar','Trate falha, timeout e resposta inválida separadamente. Não repita operações não idempotentes sem critério.',{code:'{"status":"failed",\n "erro":"arquivo ilegível"}'})]},{layout:'mosaic',title:'Oito detalhes em uma página.',items:['URL','Método','Headers','Corpo','Status','Timeout','Polling','Resposta'].map(title=>item(title,'Confira este campo na documentação do serviço antes de executar.')),source:'Demonstração de grade automática; edite, insira ou exclua um item.'},end];
  }
  if(kind==='diagramas')slides=[{...cover,subtitle:'Edite o código Mermaid no painel e veja o desenho mudar.'},{layout:'diagram',title:'Fluxo com decisão',mermaid:route,caption:'Abra Formatar → Código Mermaid. Troque um rótulo ou acrescente uma etapa.'},{layout:'diagram',title:'Uma conversa entre serviços',mermaid:'sequenceDiagram\n  participant App\n  participant API\n  participant Worker\n  App->>API: Iniciar tarefa\n  API->>Worker: Processar\n  API-->>App: id da tarefa\n  loop Até finalizar\n    App->>API: Consultar id\n    API-->>App: status\n  end\n  Worker-->>API: Resultado'},{layout:'diagram',title:'Estados de uma execução',mermaid:'stateDiagram-v2\n  [*] --> Criada\n  Criada --> Executando\n  Executando --> Finalizada\n  Executando --> Falhou\n  Falhou --> NovaTentativa\n  NovaTentativa --> Executando\n  Finalizada --> [*]'},{layout:'diagram',title:'O que entra no produto?',mermaid:'mindmap\n  root((Produto))\n    Pessoas\n      Necessidades\n      Experiência\n    Tecnologia\n      Serviços\n      Dados\n    Operação\n      Métricas\n      Melhoria'},end];
  if(kind==='lavanda')slides[0]={...cover,tone:'light',title:'Ideias que\nganham forma.',subtitle:'Estúdio lavanda · um modelo para explorar',figure:{image:'imagens/lavanda-cover.jpg',fit:'cover',radius:100}};
  return {...common,slides};
}
