// Modelos de fábrica são código; as apresentações criadas ficam somente na biblioteca.
import { COLLECTION_NAMES, COLLECTION_ASSETS, collectionDeck } from './template-collections.js';
import { LAYOUT_SAMPLES } from './layout-samples.js';
import { explorationDemo } from './exploration-demo.js';
export function demoAssets(kind) { return kind === 'lavanda' || kind === 'novidades' ? ['lavanda-cover.jpg'] : COLLECTION_ASSETS[kind] || []; }
// arquivos do projeto que o modelo traz (fora de imagens/): a planilha e as anotações da demo de novidades
export function demoProjectFiles(kind) { return kind === 'novidades' ? ['contexto/vendas.csv', 'contexto/leia-me.md'] : []; }
const item=(title,text,extra={})=>({title,text,...extra});
const route='flowchart LR\n  A([Pedido]):::hi --> B{Dados válidos?}\n  B -->|sim| C[Executar tarefa]\n  B -.->|não| D[Informar erro]:::vazado\n  C ==> E[Guardar resultado]:::em';
export const DEMO_NAMES={explorar:'Demo — explore uma ideia',lavanda:'Estúdio lavanda',executivo:'Relatório executivo',workshop:'Workshop visual',compacto:'Demo — material de consulta',avancado:'Demo — recursos avançados',diagramas:'Demo — diagramas vivos',novidades:'Demo — novidades',hidraulica:'Aula de hidráulica',algoritmos:'Aula de algoritmos',...COLLECTION_NAMES};
export function demoDeck(kind) {
  if(kind==='explorar')return explorationDemo();
  if(Object.hasOwn(COLLECTION_NAMES,kind))return collectionDeck(kind);
  if(!DEMO_NAMES[kind])throw Error('Modelo não encontrado.');
  // cada demo com a sua cara (tema, tom e figura da capa): na vitrine, as capas não podem parecer a mesma
  const LOOK={lavanda:['bauhaus','lavanda'],executivo:['prata','corporativo'],workshop:['sinal','lavanda'],compacto:['manual'],avancado:['terminal'],diagramas:['oceano'],novidades:['pop'],hidraulica:['oceano'],algoritmos:['noite']};
  const [theme,palette]=LOOK[kind]||['editorial','lavanda'];
  const common={title:DEMO_NAMES[kind],theme,...(palette?{palette}:{}),duration:15,maxWords:140};
  const COVER_FIG={compacto:{icon:'book-open',size:300},avancado:{icon:'terminal',size:300},diagramas:{icon:'workflow',size:320},novidades:{icon:'sparkles',size:320},hidraulica:{icon:'waves',size:340},algoritmos:{icon:'chart-bar',size:320}};
  const cover={layout:'cover',title:DEMO_NAMES[kind],subtitle:'Um modelo para adaptar ao seu conteúdo',kicker:'SAGADECK · MODELOS',tone:{compacto:'light',diagramas:'accent',novidades:'light',hidraulica:'light'}[kind]||'dark',...(COVER_FIG[kind]?{figure:COVER_FIG[kind]}:{})};
  const end={layout:'end',title:'O próximo passo\ncomeça aqui.',subtitle:'Duplique este modelo na biblioteca e adapte os textos.'};
  const items=[item('Descobrir','Comece pela pergunta certa.',{icon:'search'}),item('Experimentar','Teste uma hipótese com dados.',{icon:'flask-conical'}),item('Construir','Transforme o aprendizado em produto.',{icon:'blocks'}),item('Observar','Acompanhe o uso e os resultados.',{icon:'chart-column'}),item('Evoluir','Use o que aprendeu para melhorar.',{icon:'sparkles'})];
  let slides;
  if(kind==='lavanda')slides=[cover,{layout:'mosaic',title:'Cinco ideias, uma composição.',items},{layout:'ribbon',title:'Um caminho em três momentos.',items:items.slice(0,3),tone:'accent'},{layout:'quote',quote:'Uma boa apresentação deixa a ideia respirar.',by:'Princípio deste modelo',tone:'dark'},{layout:'mosaic',title:'A grade cresce com o conteúdo.',items:[...items,...items.slice(0,3)].map((x,i)=>({...x,title:`${i+1}. ${x.title}`}))},end];
  if(kind==='executivo')slides=[{...cover,subtitle:'Decisões claras, números contextualizados.'},{layout:'mosaic',title:'O que precisa de uma decisão.',items:[item('Prioridade','Melhorar o atendimento nos canais digitais.',{value:'01'}),item('Investimento','Validar o piloto antes de expandir.',{value:'02'}),item('Próximo marco','Apresentar resultados em quatro semanas.',{value:'03'})]},{layout:'stats',title:'O piloto em números',stats:[{value:'24',label:'participantes'},{value:'4',label:'semanas'},{value:'3',label:'hipóteses'}],source:'Dados fictícios para demonstrar o modelo.'},{layout:'ribbon',title:'Plano de trabalho',items:items.slice(0,4)},{layout:'compare',title:'A decisão em perspectiva',left:{title:'Continuar como está',text:'Sem custo de mudança; os problemas atuais permanecem.'},right:{title:'Testar em pequena escala',text:'Aprendizado limitado, com critérios de sucesso definidos.',hl:true}},end];
  if(kind==='workshop')slides=[{...cover,subtitle:'Aprender, experimentar, explicar.'},{layout:'question',question:'O que acontece depois do pedido?',options:['A resposta vem na hora','Recebemos um identificador','Depende do modo'],hint:'Escolha antes de avançar.'},{layout:'diagram',title:'Do pedido ao resultado',mermaid:route},{layout:'codewalk',title:'Uma chamada, três observações',language:'javascript',code:'const response = await fetch(url);\nif (!response.ok) throw new Error(response.status);\nconst dados = await response.json();\nconsole.log(dados);',steps:[{title:'Pedido',text:'A execução aguarda a resposta HTTP.',highlight:[1]},{title:'Validação',text:'Um erro HTTP interrompe o fluxo.',highlight:[2]},{title:'Resultado',text:'O JSON vira um objeto.',highlight:[3,4]}]},{layout:'dossier',title:'Para consultar depois',items:[item('URL','Identifica o recurso. Evite colocar segredos no endereço.'),item('Status','Indica o resultado HTTP. Um 200 não substitui validar o conteúdo.'),item('Corpo','Carrega os dados do pedido ou da resposta.'),item('Timeout','Limita quanto tempo a aplicação espera.')]},end];
  if(kind==='compacto') {
    const code=['import time','import requests','','def acompanhar(base, pedido, timeout=60):','    inicio = requests.post(','        f"{base}/tarefas", json=pedido, timeout=10','    )','    inicio.raise_for_status()','    tarefa = inicio.json()["id"]','    limite = time.monotonic() + timeout','','    while time.monotonic() < limite:','        resposta = requests.get(','            f"{base}/tarefas/{tarefa}", timeout=10','        )','        resposta.raise_for_status()','        dados = resposta.json()','        status = dados["status"]','','        if status == "finished":','            return dados["resultado"]','        if status == "failed":','            raise RuntimeError(dados["erro"])','','        time.sleep(1)','','    raise TimeoutError("A tarefa não terminou")'].join('\n');
    slides=[{...cover,subtitle:'Código, payloads e instruções no mesmo material.'},{layout:'code',title:'No palco: explique a ideia.',language:'python',code:'resposta = iniciar(pedido)\nid = resposta["id"]\n\nwhile not terminou(id):\n    esperar(1)\n\nmostrar(resultado(id))',notes:'Versão conceitual para explicar ao público; não é código executável.'},{layout:'code',title:'Na consulta: o exemplo completo.',density:'dense',language:'python',code,source:'API fictícia. Ajuste as rotas e instale requests. 27 linhas sem ocultar o final.'},{layout:'dossier',title:'Como ler a resposta',items:[item('Identificador','Guarde o id devolvido ao iniciar. Ele é usado nas consultas seguintes.',{code:'{"id":"tarefa-42","status":"started"}'}),item('Enquanto executa','Consulte com um intervalo definido e limite total de espera.',{code:'{"id":"tarefa-42","status":"running"}'}),item('Ao finalizar','Valide o status antes de ler o resultado de cada etapa.',{code:'{"status":"finished",\n "resultado":[\n  {"etapa":"ocr","paginas":12},\n  {"etapa":"resumo","texto":"…"}\n ]}'}),item('Se falhar','Trate falha, timeout e resposta inválida separadamente. Não repita operações não idempotentes sem critério.',{code:'{"status":"failed",\n "erro":"arquivo ilegível"}'})]},{layout:'mosaic',title:'Oito detalhes em uma página.',items:['URL','Método','Headers','Corpo','Status','Timeout','Polling','Resposta'].map(title=>item(title,'Confira este campo na documentação do serviço antes de executar.')),source:'Demonstração de grade automática; edite, insira ou exclua um item.'},end];
  }
  if(kind==='diagramas')slides=[{...cover,subtitle:'Edite o código Mermaid no painel e veja o desenho mudar.'},{layout:'diagram',title:'Fluxo com decisão',mermaid:route,caption:'Abra Formatar → Código Mermaid. Troque um rótulo ou acrescente uma etapa.'},{layout:'diagram',title:'Uma conversa entre serviços',mermaid:'sequenceDiagram\n  participant App\n  participant API\n  participant Worker\n  App->>API: Iniciar tarefa\n  API->>Worker: Processar\n  API-->>App: id da tarefa\n  loop Até finalizar\n    App->>API: Consultar id\n    API-->>App: status\n  end\n  Worker-->>API: Resultado'},{layout:'diagram',title:'Estados de uma execução',mermaid:'stateDiagram-v2\n  [*] --> Criada\n  Criada --> Executando\n  Executando --> Finalizada\n  Executando --> Falhou\n  Falhou --> NovaTentativa\n  NovaTentativa --> Executando\n  Finalizada --> [*]'},{layout:'diagram',title:'O que entra no produto?',mermaid:'mindmap\n  root((Produto))\n    Pessoas\n      Necessidades\n      Experiência\n    Tecnologia\n      Serviços\n      Dados\n    Operação\n      Métricas\n      Melhoria'},end];
  if(kind==='avancado')slides=[
    {...cover,subtitle:'Quando a apresentação também precisa servir de consulta.'},
    {layout:'code',title:'Exemplo completo: acompanhar uma tarefa',density:'dense',language:'python',code:'import time\n\nimport requests\n\ndef acompanhar(base, tarefa, timeout=60):\n    limite = time.monotonic() + timeout\n    while time.monotonic() < limite:\n        resposta = requests.get(\n            f"{base}/tarefas/{tarefa}",\n            timeout=10,\n        )\n        resposta.raise_for_status()\n        dados = resposta.json()\n        status = dados["status"]\n\n        if status == "finished":\n            return dados["resultado"]\n\n        if status == "failed":\n            raise RuntimeError(dados["erro"])\n\n        time.sleep(1)\n\n    raise TimeoutError("A tarefa não terminou")',source:'Exemplo demonstrativo completo. As linhas numeradas acompanham o código até o final.'},
    {layout:'dossier',title:'Dados para acompanhar a tarefa',items:[item('Identificador','Guarde o id devolvido ao iniciar o processamento.',{code:'{"id":"tarefa-42","status":"started"}'}),item('Enquanto executa','Consulte o estado em intervalos definidos e com timeout.',{code:'{"id":"tarefa-42","status":"running"}'}),item('Resultado','Leia o conteúdo somente depois de confirmar o estado final.',{code:'{"status":"finished","resultado":{"paginas":12}}'}),item('Falha','Exiba a causa sem repetir operações não idempotentes.',{code:'{"status":"failed","erro":"arquivo ilegível"}'})]},
    {layout:'mosaic',title:'Oito campos para revisar',items:['URL','Método','Headers','Corpo','Status','Timeout','Polling','Resposta'].map((title)=>item(title,'Confira este campo na documentação antes de executar.'))},
    {layout:'statement',kicker:'AVISO · SEGURANÇA',text:'Não coloque tokens no código ou na apresentação.',add:{aviso:{tipo:'perigo',titulo:'Segredo exposto',texto:'Use Ambientes para guardar chaves na sua máquina. Elas não devem entrar no YAML do deck.'}}},
    end,
  ];
  // um slide de cada recurso novo; a pasta do projeto já traz contexto/vendas.csv (aba Arquivos › planilha)
  if(kind==='novidades'){
    const vendas={labels:['jan','fev','mar','abr','mai','jun'],series:[{name:'Norte',values:[10.5,12,15,17,16,19]},{name:'Sul',values:[7,9,8,11,13,14]}]};
    slides=[
      {...cover,subtitle:'Carrossel, gráficos do Excel, fórmulas vivas, dinâmicas a dois e a pasta do projeto.',kicker:'SAGADECK · NOVIDADES'},
      {layout:'dossier',title:'Onde está cada novidade',items:[
        item('Pasta do projeto','Aba Arquivos, à esquerda: a pasta da apresentação, com contexto/ para anexos, prints e planilhas.',{icon:'folder-tree'}),
        item('Planilha → gráfico','Abra contexto/vendas.csv: o Studio lê os tipos das colunas e sugere gráficos, com ou sem IA.',{icon:'table'}),
        item('Colar do Excel','No gráfico de dados, Formatar › Dados: Ctrl+V de uma tabela preenche a planilha.',{icon:'clipboard-paste'}),
        item('Fórmulas vivas','Fórmulas e funções: escreva a fórmula; cada letra vira um controle deslizante.',{icon:'sigma'}),
        item('Dinâmicas a dois','Duelo de commits, dois terminais e turnos: um quadro por clique.',{icon:'users'}),
        item('Carrossel e zoom','Carrossel em roda ou em anéis; o Foco guiado aproxima devagar de cada detalhe.',{icon:'sparkles'})]},
      {...LAYOUT_SAMPLES.carousel,title:'Carrossel em roda'},
      {...LAYOUT_SAMPLES.carousel,title:'Carrossel em anéis',style:'rings'},
      {layout:'chart',title:'Vendas por região, direto da planilha',chart:{chart:'line',csv:'contexto/vendas.csv',...vendas,xLabel:'Mês',yLabel:'R$ milhões'},side:'Este gráfico lê **contexto/vendas.csv**. Mude um número lá (aba Arquivos) e ele acompanha.'},
      {layout:'chart',title:'Colado do Excel: colunas agrupadas',chart:{chart:'column',...vendas,xLabel:'Mês'},side:'No Formatar, a planilha do gráfico aceita **Ctrl+V** de uma tabela do Excel: a primeira linha vira o nome das séries.'},
      {...LAYOUT_SAMPLES.science},
      {layout:'science',title:'Queda livre: medida × teoria',plot:{functions:[{fn:'h0 - g*x^2/2',name:'teoria'}],x:[0,2],params:{h0:{value:20,min:5,max:40,label:'altura'},g:{value:9.8,min:1,max:25,label:'gravidade'}},points:'t\tmedido\n0\t20\n0,5\t18,9\n1\t15,2\n1,5\t8,8\n1,9\t2,1',pointsName:'medido'}},
      {...LAYOUT_SAMPLES.duel},
      {...LAYOUT_SAMPLES.terminals,turns:[...LAYOUT_SAMPLES.terminals.turns]},
      {...LAYOUT_SAMPLES.turns},
      {layout:'spotlight',title:'Foco guiado com zoom lento',image:'imagens/lavanda-cover.jpg',zoom:true,hotspots:[{title:'A imagem inteira',text:'O primeiro passo mostra tudo.',x:0,y:0,width:100,height:100,zoom:false},{title:'Um detalhe',text:'A imagem aproxima devagar do ponto da vez.',x:30,y:25,width:30,height:35},{title:'Outro detalhe',text:'Cada foco pode ter o seu zoom.',x:60,y:55,width:25,height:30,zoom:2.4}]},
      end,
    ];
  }
  // aula de engenharia: equações, curva que se mexe, calculadora ao vivo, exercício resolvido passo a passo
  if(kind==='hidraulica')slides=[
    {...cover,kicker:'HIDRÁULICA · AULA 3',title:'Escoamento em tubos:\ndo laminar ao turbulento',subtitle:'Navier–Stokes, número de Reynolds e perda de carga, com contas e um exercício resolvido.'},
    {layout:'dossier',title:'Três ideias para hoje',items:[item('Viscosidade','A resistência do fluido a escoar. Água a 20 °C: ν ≈ 1,0 × 10⁻⁶ m²/s.',{icon:'droplet'}),item('Número de Reynolds','Compara a inércia com a viscosidade: Re = VD/ν. Abaixo de ~2300 o escoamento é laminar.',{icon:'waves'}),item('Perda de carga','A energia que o atrito com a parede consome: h_f = f (L/D) V²/2g.',{icon:'trending-down'})]},
    {layout:'science',title:'As equações de Navier–Stokes (incompressível)',equations:[{label:'Continuidade: o que entra sai',latex:'\\nabla \\cdot \\mathbf{u} = 0'},{label:'Quantidade de movimento',latex:'\\rho\\left(\\frac{\\partial \\mathbf{u}}{\\partial t} + \\mathbf{u}\\cdot\\nabla\\mathbf{u}\\right) = -\\nabla p + \\mu \\nabla^2 \\mathbf{u} + \\rho \\mathbf{g}'},{label:'Inércia ÷ viscosidade',latex:'Re = \\frac{\\rho V D}{\\mu} = \\frac{V D}{\\nu}'}],plot:false},
    {layout:'science',title:'Laminar: o perfil de velocidade é uma parábola',equations:[{label:'Hagen–Poiseuille',latex:'u(r) = u_{max}\\left(1 - \\frac{r^2}{R^2}\\right)'},{label:'Velocidade média',latex:'V = \\frac{u_{max}}{2}'}],plot:{functions:[{fn:'umax*(1 - (x/R)^2)',name:'u(r)'}],x:[-0.05,0.05],params:{umax:{value:2,min:0.5,max:4,label:'u máx (m/s)'},R:{value:0.05,min:0.01,max:0.05,step:0.005,label:'raio (m)'}}}},
    {layout:'calc',title:'Qual é o regime? Mexa na velocidade e no diâmetro',inputs:{V:{label:'Velocidade',latex:'V',value:1.5,min:0.01,max:4,step:0.01,unit:'m/s'},D:{label:'Diâmetro',latex:'D',value:0.05,min:0.005,max:0.3,step:0.005,unit:'m'},nu:{label:'Viscosidade cinemática (água, 20 °C)',latex:'\\nu = 1{,}004\\times10^{-6}\\ \\mathrm{m^2/s}',value:0.000001004,fixed:true},eps:{label:'Rugosidade (PVC)',latex:'\\varepsilon = 0{,}05\\ \\mathrm{mm}',value:0.00005,fixed:true}},
      outputs:[{name:'Re',label:'Número de Reynolds',latex:'Re = \\frac{VD}{\\nu}',fn:'V*D/nu',decimals:0},{name:'regime',label:'Regime',of:'Re',cases:[{below:2300,text:'Laminar',color:'s3'},{below:4000,text:'Transição',color:'em'},{text:'Turbulento',color:'hi'}],scale:{min:100,max:1000000,log:true}},{name:'f',label:'Fator de atrito',latex:'f = \\frac{64}{Re}\\ \\text{ou Swamee–Jain}',of:'Re',cases:[{below:2300,fn:'64/Re'},{fn:'0.25/(log10(eps/(3.7*D) + 5.74/Re^0.9))^2'}],decimals:4}],note:'Abaixo de 2300 vale f = 64/Re; acima de 4000, Swamee–Jain (explícita, no lugar de Colebrook).'},
    {layout:'solution',title:'Exercício: perda de carga num tubo de PVC',problem:'Água a 20 °C escoa a 1,5 m/s num tubo de PVC de 50 mm. Qual é o regime e quanto de carga se perde em 100 m?',givens:[{symbol:'V',value:'1,5',unit:'m/s',label:'velocidade'},{symbol:'D',value:'0,05',unit:'m',label:'diâmetro'},{symbol:'L',value:'100',unit:'m',label:'comprimento'},{latex:'\\nu = 1{,}004\\times10^{-6}\\ \\mathrm{m^2/s}',label:'viscosidade'},{latex:'\\varepsilon = 0{,}05\\ \\mathrm{mm}',label:'rugosidade'}],find:'Re,\\ f,\\ h_f',
      steps:[{text:'Reynolds decide o regime',latex:'Re = \\frac{VD}{\\nu} = \\frac{1{,}5 \\cdot 0{,}05}{1{,}004\\times10^{-6}} \\approx 74\\,700'},{text:'Re > 4000: turbulento. A rugosidade relativa entra na conta',latex:'\\varepsilon/D = \\frac{0{,}05}{50} = 0{,}001'},{text:'Fator de atrito (Swamee–Jain)',latex:'f = \\frac{0{,}25}{\\left[\\log\\left(\\frac{\\varepsilon}{3{,}7D} + \\frac{5{,}74}{Re^{0{,}9}}\\right)\\right]^2} \\approx 0{,}0230'},{text:'Darcy–Weisbach',latex:'h_f = f\\,\\frac{L}{D}\\,\\frac{V^2}{2g} = 0{,}0230 \\cdot \\frac{100}{0{,}05} \\cdot \\frac{1{,}5^2}{2 \\cdot 9{,}81}'}],
      answer:{latex:'h_f \\approx 5{,}3\\ \\mathrm{m}',text:'Turbulento; perde cerca de 5,3 m de coluna d’água em 100 m.'}},
    {layout:'science',title:'Diagrama de Moody (versão explícita)',equations:[{label:'Laminar',latex:'f = 64/Re'},{label:'Turbulento (Swamee–Jain)',latex:'f = 0{,}25\\,/\\,[\\log(\\varepsilon/3{,}7D + 5{,}74/Re^{0{,}9})]^2'}],plot:{functions:[{fn:'64/x',name:'laminar: 64/Re'},{fn:'0.25/(log10(r/3.7 + 5.74/x^0.9))^2',name:'turbulento'}],x:[600,10000000],xlog:true,ylog:true,params:{r:{value:0.001,min:0.00001,max:0.05,step:0.00001,label:'ε/D'}},layout:{xaxis:{title:{text:'Re'}},yaxis:{title:{text:'f'}}}}},
    {layout:'compare',title:'Laminar × turbulento',left:{label:'Laminar',title:'Camadas que deslizam',text:'Re < 2300: perfil parabólico; o atrito depende só de Re.',items:['f = 64/Re','perda ∝ V']},right:{label:'Turbulento',title:'Redemoinhos que misturam',text:'Re > 4000: perfil achatado; a rugosidade da parede pesa.',items:['f por Colebrook / Moody','perda ∝ V² (aprox.)'],hl:true}},
    {layout:'question',question:'Água a 0,5 m/s num tubo de 4 mm: qual é o regime?',options:['Laminar','Transição','Turbulento'],hint:'Re = VD/ν ≈ 2000.'},
    end,
  ];
  // aula de computação: o algoritmo rodando de verdade (barras, código e contadores) e a complexidade
  if(kind==='algoritmos')slides=[
    {...cover,kicker:'ALGORITMOS · AULA 5',title:'Ordenar e buscar:\nvendo o algoritmo pensar',subtitle:'Cada clique é um passo. O botão Tocar anda sozinho.'},
    {layout:'algo',title:'Bubble sort: o maior sobe como bolha',algorithm:'bubble',array:[5,1,4,2,8,3]},
    {layout:'algo',title:'Insertion sort: como organizar cartas na mão',algorithm:'insertion',array:[5,1,4,2,8,3]},
    {layout:'algo',title:'Quicksort: escolhe um pivô e divide',algorithm:'quick',array:[7,2,9,4,3,8,1,6]},
    {layout:'science',title:'Por que isso importa: n² × n log n',equations:[{label:'Bubble, insertion, selection',latex:'O(n^2)'},{label:'Merge sort, quicksort (médio)',latex:'O(n \\log n)'}],plot:{functions:[{fn:'x^2',name:'n²'},{fn:'x*log2(x)',name:'n log n'}],x:[1,64],layout:{xaxis:{title:{text:'n (tamanho do vetor)'}},yaxis:{title:{text:'operações'}}}}},
    {layout:'algo',title:'Busca linear: olha um por um',algorithm:'linear',array:[2,5,8,12,16,23,38,56,72,91],target:23},
    {layout:'algo',title:'Busca binária: descarta metade a cada passo',algorithm:'binary',array:[2,5,8,12,16,23,38,56,72,91],target:23},
    {layout:'question',question:'Numa lista ordenada de 1 milhão de nomes, quantas comparações a busca binária faz no pior caso?',options:['Cerca de 20','Cerca de 1.000','Cerca de 500.000'],hint:'log₂(1.000.000) ≈ 20.'},
    {layout:'codewalk',title:'A busca binária em Python',language:'python',code:'def busca_binaria(v, alvo):\n    ini, fim = 0, len(v) - 1\n    while ini <= fim:\n        meio = (ini + fim) // 2\n        if v[meio] == alvo:\n            return meio\n        if v[meio] < alvo:\n            ini = meio + 1\n        else:\n            fim = meio - 1\n    return -1',steps:[{title:'Os limites',text:'ini e fim marcam a faixa onde o alvo ainda pode estar.',highlight:[2]},{title:'O meio',text:'Divisão inteira: // descarta a parte fracionária.',highlight:[4]},{title:'Metade fora',text:'Cada volta descarta metade da faixa.',highlight:[7,8,9,10]},{title:'Não achou',text:'A faixa ficou vazia: devolve -1.',highlight:[11]}]},
    end,
  ];
  if(kind==='lavanda')slides[0]={...cover,tone:'light',title:'Ideias que\nganham forma.',subtitle:'Estúdio lavanda · um modelo para explorar',figure:{image:'imagens/lavanda-cover.jpg',fit:'cover',radius:100}};
  return {...common,slides};
}
