// Conteúdo de exemplo de cada layout — usado na galeria de layouts do Studio (prévia no tema do deck).
export const LAYOUT_INFO = {
  cover: ["Capa", "Abertura com título, subtítulo e autor"],
  section: ["Seção", "Abre um novo ato ou capítulo"],
  statement: ["Frase de impacto", "Uma ideia em letras grandes"],
  headline: ["Manchete", "Uma frase enorme ocupando o slide"],
  quote: ["Citação", "Uma fala com autor"],
  number: ["Número grande", "Um número que conta até o valor"],
  split: ["Texto e figura", "Texto de um lado, figura do outro"],
  full: ["Página inteira", "Imagem ou figura ocupando tudo"],
  cards: ["Cartões", "2 a 4 cartões com ícone"],
  bento: ["Mosaico", "Blocos de tamanhos diferentes (bento)"],
  stats: ["Indicadores", "KPIs com tendência"],
  steps: ["Etapas", "Processo em passos conectados"],
  funnel: ["Funil", "Etapas que afunilam"],
  pyramid: ["Pirâmide", "Níveis do topo à base"],
  list: ["Lista", "Itens numerados grandes"],
  agenda: ["Agenda", "Seções com a atual destacada"],
  timeline: ["Linha do tempo", "Eventos em sequência"],
  chart: ["Gráfico", "Gráfico com comentário"],
  compare: ["Comparação", "A × B lado a lado"],
  matrix: ["Matriz 2×2", "Quatro quadrantes"],
  question: ["Pergunta", "Pergunta para a plateia com timer"],
  poll: ["Enquete", "Votação ao vivo"],
  image: ["Imagem", "Imagem em tela cheia com legenda"],
  code: ["Código", "Código com linhas destacadas"],
  codewalk: ["Código guiado", "Explique uma linha por vez, com destaques e saída simulada"],
  api: ["API ao vivo", "Requisição que executa na hora (tipo Postman): síncrono, polling ou streaming, com código curl/Python"],
  spotlight: ["Foco guiado", "Conduza o olhar por detalhes de uma imagem ou diagrama"],
  video: ["Vídeo", "Cartão que abre um vídeo"],
  blocks: ["Livre (blocos)", "Monte com blocos em linhas e colunas"],
  canvas: ["Livre (posições)", "Posicione cada elemento à mão"],
  references: ["Referências", "Fontes em duas colunas"],
  end: ["Encerramento", "Obrigado e contatos"],
};

export const LAYOUT_SAMPLES = {
  cover: { layout: "cover", kicker: "Evento 2026", title: "Título da ==apresentação==", subtitle: "Um subtítulo curto", author: "Seu nome", figure: { icon: "rocket", size: 320 } },
  section: { layout: "section", number: 2, kicker: "Parte dois", title: "O problema" },
  statement: { layout: "statement", kicker: "A ideia", text: "Uma frase que ==muda tudo==." },
  headline: { layout: "headline", text: "78% ==desistem==", caption: "no segundo passo" },
  quote: { layout: "quote", quote: "Dados vencem opiniões.", by: "Alguém sábio" },
  number: { layout: "number", value: 42, suffix: "%", label: "mais rápido" },
  split: { layout: "split", title: "Texto e figura", bullets: ["Primeiro ponto", "Segundo ponto"], figure: { icon: "lightbulb", size: 300 } },
  full: { layout: "full", figure: { chart: "donut", value: 72, center: "72%" }, title: "Figura em página inteira", overlay: "left" },
  cards: { layout: "cards", title: "Três pilares", items: [{ icon: "shield", title: "Seguro" }, { icon: "zap", title: "Rápido" }, { icon: "heart", title: "Simples" }] },
  bento: { layout: "bento", title: "Em um olhar", tiles: [{ value: "8,4 mi", title: "Receita", hl: true }, { icon: "users", title: "NPS 91" }, { icon: "rocket", title: "3 lançamentos" }, { icon: "globe", title: "2 países" }, { icon: "check", title: "Zero falhas" }] },
  stats: { layout: "stats", title: "Resultados", stats: [{ value: "+42%", label: "Receita" }, { value: "0,6%", label: "Churn" }, { value: "91", label: "NPS" }] },
  steps: { layout: "steps", title: "Como funciona", steps: [{ title: "Coletar" }, { title: "Analisar" }, { title: "Agir" }] },
  funnel: { layout: "funnel", title: "Funil", stages: [{ title: "Visitas", value: "120k" }, { title: "Cadastro", value: "18k" }, { title: "Pagantes", value: "900" }] },
  pyramid: { layout: "pyramid", title: "Pirâmide", levels: [{ title: "Topo" }, { title: "Meio" }, { title: "Base" }] },
  list: { layout: "list", title: "Lista", items: ["Primeiro item", "Segundo item", "Terceiro item"] },
  agenda: { layout: "agenda", title: "Agenda", current: 2, items: [{ title: "Abertura" }, { title: "O problema" }, { title: "A solução" }] },
  timeline: { layout: "timeline", title: "Linha do tempo", events: [{ when: "2019", title: "Início" }, { when: "2022", title: "Virada" }, { when: "2026", title: "Hoje" }] },
  chart: { layout: "chart", title: "Crescimento", chart: { chart: "column", data: [{ label: "A", value: 30 }, { label: "B", value: 55 }, { label: "C", value: 80 }] }, side: "Subiu ==2,6×==" },
  compare: { layout: "compare", title: "Antes × depois", left: { label: "Antes", value: "3 dias" }, right: { label: "Depois", value: "2 h", hl: true } },
  matrix: { layout: "matrix", title: "Matriz", x: ["Fácil", "Difícil"], y: ["Alto impacto", "Baixo impacto"], cells: [{ title: "Faça já", hl: true }, { title: "Planeje" }, { title: "Delegue" }, { title: "Evite" }] },
  question: { layout: "question", question: "Qual você escolheria?", options: ["Opção A", "Opção B", "Opção C"], timer: 30 },
  poll: { layout: "poll", question: "Vote agora", id: "exemplo", options: ["Sim", "Não", "Talvez"] },
  image: { layout: "image", figure: { picto: "scene", name: "desk" }, title: "Imagem em tela cheia" },
  code: { layout: "code", title: "Código", code: "def ola():\n    return 'mundo'", highlight: [2] },
  codewalk: { layout: "codewalk", kicker: "Laboratório · API", title: "Uma API em ==três movimentos==", filename: "primeira-api.js", language: "JavaScript",
    code: "const resposta = await fetch('/api/aulas');\n\nconst aulas = await resposta.json();\n\nconst ativas = aulas.filter(aula => aula.ativa);\n\nconsole.log(ativas.length);",
    steps: [{ title: "Faça a pergunta", text: "fetch envia o pedido. await dá tempo para a resposta chegar.", highlight: [1], output: "GET /api/aulas → 200 OK" },
      { title: "Transforme a resposta", text: "O corpo JSON vira uma lista que o código consegue usar.", highlight: [3], output: "[{ id: 1, ativa: true },\n { id: 2, ativa: false }]" },
      { title: "Escolha o que importa", text: "Só as aulas ativas passam pelo filtro. Qual será a saída?", highlight: [5, 7], output: "1" }] },
  spotlight: { layout: "spotlight", kicker: "Olhar de quem programa", title: "O detalhe que ==muda tudo==", caption: "Inspeção de uma resposta HTTP · clique nos detalhes para explorar",
    figure: { svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 600"><rect width="1000" height="600" fill="#101725"/><rect width="1000" height="70" fill="#1d273a"/><circle cx="30" cy="35" r="7" fill="#f09282"/><circle cx="55" cy="35" r="7" fill="#e5bd76"/><circle cx="80" cy="35" r="7" fill="#93c1a4"/><g font-family="monospace"><text x="125" y="44" font-size="22" fill="#a1adc4">API EXPLORER / aulas</text><rect x="40" y="110" width="920" height="84" rx="10" fill="#263348"/><text x="66" y="162" font-size="28" fill="#9ce3c3">GET</text><text x="145" y="162" font-size="28" fill="#e8edf5">/api/aulas</text><rect x="40" y="230" width="920" height="56" rx="8" fill="#142d2a"/><text x="65" y="267" font-size="24" fill="#9ce3c3">200 OK</text><text x="780" y="267" font-size="22" fill="#9ce3c3">42 ms</text><text x="55" y="341" font-size="25" fill="#c0cee9">{</text><text x="90" y="390" font-size="25" fill="#9fc3ff">"aulas": [</text><text x="125" y="439" font-size="25" fill="#e8edf5">{ "id": 1, "ativa": true }</text><text x="90" y="488" font-size="25" fill="#9fc3ff">]</text><text x="55" y="537" font-size="25" fill="#c0cee9">}</text></g></svg>' },
    hotspots: [{ x: 4, y: 18, width: 92, height: 15, title: "O pedido", text: "O verbo GET consulta o recurso. A rota identifica a coleção de aulas." },
      { x: 4, y: 38, width: 92, height: 10, title: "A confirmação", text: "200 OK confirma o sucesso. O tempo ajuda a investigar a experiência do usuário." },
      { x: 5, y: 52, width: 78, height: 39, title: "Os dados", text: "A estrutura JSON é o contrato que o front-end precisa entender." }] },
  api: { layout: "api", kicker: "Ao vivo", title: "Pergunte ao ==modelo==", request: { method: "POST", url: "{{base}}/chat", body: { messages: [{ role: "user", content: "Explique RAG em uma frase" }] } }, answer: "$.choices[0].message.content" },
  video: { layout: "video", title: "Assista", url: "https://example.com", label: "Assistir" },
  blocks: { layout: "blocks", title: "Blocos livres", content: [{ row: [{ lead: "Esquerda" }, { lead: "Direita" }] }] },
  canvas: { layout: "canvas", elements: [{ h2: "Livre", x: 200, y: 200 }, { icon: "star", size: 200, x: 1200, y: 400 }] },
  references: { layout: "references", title: "Fontes", items: ["Autor (2024). Título.", "Outro (2025). Estudo."] },
  end: { layout: "end", title: "Obrigado.", subtitle: "Perguntas?", contacts: ["seu@email.com"] },
};
