import { portalExample } from '../portal-scene.js';
import { playgroundExample } from '../playground.js';
// Conteúdo de exemplo de cada layout — usado na galeria de layouts do Studio (prévia no tema do deck).
import { graphLabExample } from '../graph-lab.js';
import { codeLabExample } from '../code-lab.js';
export const LAYOUT_INFO = {
  portal: ["Portal e transformação", "Entre em um elemento, transforme o cenário e revele texto integrado ao ambiente"],
  playground: ["Experiência personalizada", "HTML, CSS e JavaScript interativos em um frame isolado"],
  codelab: ['Código explorável', 'Alunos alteram código e entradas, executam offline e acompanham estruturas e variáveis passo a passo'],
  graphlab: ['Rede explorável', 'Navegue pelos nós, teste rotas, altere custos, remova conexões e reorganize a rede ao vivo'],
  mosaic: ["Grade adaptável", "De 1 a 12 itens: as colunas se ajustam à quantidade e ao tamanho do texto"],
  ribbon: ["Cápsulas", "Etapas em painéis arredondados, com colunas automáticas"],
  dossier: ["Página de consulta", "Material compacto com seções, código e notas na mesma página"],
  decisionlab: ["Laboratório de decisões", "Compare automação e revisão humana com premissas ajustáveis ao vivo"],
  solution: ["Exercício resolvido", "Enunciado e dados de um lado; cada clique revela o próximo passo da conta, até a resposta em destaque"],
  calc: ["Calculadora ao vivo", "Mexa nas entradas e veja as fórmulas, as faixas (\"laminar\", \"turbulento\"…) e a régua mudarem na hora"],
  algo: ["Algoritmo animado", "Qualquer algoritmo rodando de verdade (ordenação, busca em texto, grafo, árvore ou o seu código em Python): as estruturas desenhadas, a linha do código, as variáveis como num depurador e o botão Tocar"],
  carousel: ["Carrossel", "Um item por clique com foto e texto: roda em semicírculo que gira, ou a foto em anéis que giram e travam"],
  duel: ["Duelo de commits", "Duas pessoas no mesmo arquivo, um clique por jogada: o Git calcula push recusado, merge e conflito, e o grafo cresce"],
  terminals: ["Dois terminais", "Comandos digitados lado a lado; com o roteiro do duelo, a saída do Git (e o git log --graph) sai calculada"],
  turns: ["Turnos a dois", "Code review, cliente × servidor, debate ou role-play: uma fala por clique, alternando os lados"],
  science: ["Fórmulas e funções", "Escreva a fórmula e ela vira curva; cada letra vira um controle deslizante. Aceita pontos colados do Excel e superfície 3D"],
  infographic: ["Infográfico", "Arco, ramos, lados, trilhas ou metrô: de 2 a 8 itens coloridos em volta de um centro"],
  diagram: ["Diagrama", "Fluxograma, sequência, estados, UML, jornada, mapa mental (Mermaid) nas cores do tema"],
  scenography: ["Texto no cenário", "13 composições (palco, terminal, café, embarque, pregão, cinema, revista…), sem animação"],
  cover: ["Capa", "Abertura com título, subtítulo e autor"],
  section: ["Seção", "Abre um novo ato ou capítulo"],
  statement: ["Frase de impacto", "Uma ideia em letras grandes"],
  calendar: ["Calendário", "Datas num calendário: um cartão por mês com o mini calendário e os eventos marcados; o que não tem data vai em \"sem data\""],
  poster: ["Pôster (infográfico)", "Uma página como figura de revista científica: ilustração principal e painéis com letra (a, b, c), desenho, texto curto e números"],
  definition: ["Definição", "O termo em destaque, a origem da palavra em partes e a definição, com um ícone ilustrativo"],
  headline: ["Manchete", "Uma frase enorme ocupando o slide"],
  quote: ["Citação", "Uma fala com autor"],
  onepage: ["One-page", "Tudo numa página: jornada com ícones, problema com números, solução e um painel (números, gráficos, mapa por UF)"],
  status: ["Status semanal", "Feito, em andamento, bloqueios, riscos e próximos passos, com saúde, avanço e telas da semana"],
  hub: ["Mapa de caminhos", "Opções clicáveis que levam cada uma à sua parte da apresentação (processo com vários caminhos)"],
  number: ["Número grande", "Um número que conta até o valor"],
  split: ["Texto e figura", "Texto de um lado, figura do outro"],
  full: ["Página inteira", "Imagem ou figura ocupando tudo"],
  cards: ["Cartões", "2 a 4 cartões com ícone"],
  bento: ["Mosaico", "Blocos de tamanhos diferentes (bento)"],
  stats: ["Indicadores", "KPIs com tendência"],
  steps: ["Etapas", "Processo em passos conectados"],
  funnel: ["Funil", "Etapas que afunilam"],
  pyramid: ["Pirâmide", "Níveis do topo à base"],
  list: ["Lista", "Itens numerados grandes"],
  agenda: ["Agenda", "Seções com a atual destacada"],
  timeline: ["Linha do tempo", "Eventos em sequência"],
  chart: ["Gráfico de dados", "Barras, colunas, linhas, rosca: cole a tabela do Excel ou digite os valores"],
  table: ["Tabela", "Tabela de verdade nas cores do tema: cole do Excel, destaque linha e total"],
  map: ["Mapa", "Pontos, linhas e áreas sobre o mapa ao vivo: da planilha do projeto, de GeoJSON/GPX/KML ou valores por estado; cor por categoria, cartão ao clicar, uma camada por clique"],
  compare: ["Comparação", "A × B lado a lado"],
  matrix: ["Matriz 2×2", "Quatro quadrantes"],
  question: ["Pergunta", "Pergunta para a plateia com timer"],
  poll: ["Enquete", "Votação ao vivo"],
  image: ["Imagem", "Imagem em tela cheia com legenda"],
  code: ["Código", "Código com linhas destacadas"],
  codewalk: ["Código guiado", "Explique uma linha por vez, com destaques e saída simulada"],
  api: ["API ao vivo", "Requisição que executa na hora (tipo Postman): síncrono, polling ou streaming, com código curl/Python"],
  spotlight: ["Foco guiado", "Conduza o olhar por detalhes de uma imagem ou diagrama"],
  kinetic: ["Tipografia cinética", "Frases em sequência viram parte da cena com ritmo e estilos tipográficos que mudam"],
  video: ["Vídeo", "Player YouTube online ou MP4 incorporado"],
  blocks: ["Livre (blocos)", "Monte com blocos em linhas e colunas"],
  canvas: ["Livre (posições)", "Posicione cada elemento à mão"],
  references: ["Referências", "Fontes em duas colunas"],
  end: ["Encerramento", "Obrigado e contatos"],
};

// Como pedir cada layout à IA, em português comum: aparece no "Conheça o SagaDeck" (src/studio/tour.js), para quem vê
// o recurso saber a frase que o gera. Exemplos de áreas variadas, nunca de um setor só.
export const LAYOUT_ASK = {
  portal: "Abra a palestra entrando numa porta que transforma o cenário e revela o tema",
  playground: "Faça um slide interativo em que a plateia mexe num controle e vê a cor do céu mudar",
  codelab: "Monte um exercício de código em que os alunos alteram a entrada e executam passo a passo",
  graphlab: "Mostre a rede de metrô da cidade e deixe testar a rota mais curta tirando uma estação",
  mosaic: "Liste as seis frentes do projeto num mosaico que se ajusta sozinho",
  ribbon: "Mostre as três fases da obra em cápsulas, uma ao lado da outra",
  dossier: "Faça uma página de consulta com os comandos e as respostas da API, para guardar",
  decisionlab: "Compare revisão humana e automação com premissas que eu possa ajustar ao vivo",
  solution: "Resolva passo a passo quanto rende uma aplicação de R$ 1.000 a 1% ao mês em três anos",
  calc: "Faça uma calculadora do consumo de energia de uma casa, com faixas de baixo, médio e alto",
  algo: "Mostre a busca binária rodando de verdade, com o código e as variáveis",
  carousel: "Apresente cinco destinos de viagem, um por clique, com foto e uma frase",
  duel: "Simule duas pessoas editando o mesmo arquivo no Git até dar conflito",
  terminals: "Mostre dois terminais lado a lado: um faz push e o outro puxa a mudança",
  turns: "Encene um diálogo entre cliente e atendente, uma fala por clique",
  science: "Mostre a parábola y = ax² + bx + c com controles para a, b e c",
  infographic: "Faça um infográfico com os cinco pilares da sustentabilidade em volta de um centro",
  diagram: "Desenhe o fluxo de atendimento de um pedido, da chegada à entrega",
  scenography: "Abra com a frase \"Além do óbvio\" num cenário de palco",
  cover: "Faça a capa da palestra sobre energia solar, com o meu nome e a data",
  section: "Abra a segunda parte, sobre os resultados",
  statement: "Uma frase de impacto: a água mais barata é a que não se desperdiça",
  calendar: "Mostre num calendário as datas das oficinas do semestre",
  poster: "Faça um pôster de uma página explicando como funciona uma placa solar",
  definition: "Defina \"sustentabilidade\", com a origem da palavra",
  headline: "Uma manchete enorme: 40% da água tratada se perde no caminho",
  quote: "Ponha a citação de Paulo Freire sobre ensinar, com o autor",
  onepage: "Resuma o projeto numa página: jornada, problema com números, solução e painel",
  status: "Faça o status da semana: feito, em andamento, bloqueios e próximos passos",
  hub: "Monte um menu em que a plateia escolhe o caminho: iniciante, intermediário ou avançado",
  number: "Mostre o número 1,2 milhão de visitantes, contando até ele",
  split: "Explique o ciclo da água com o texto de um lado e uma ilustração do outro",
  full: "Uma foto de floresta ocupando o slide inteiro",
  cards: "Três cartões com os benefícios do programa, cada um com ícone",
  bento: "Monte um mosaico de blocos com os destaques do ano",
  stats: "Mostre quatro indicadores do trimestre com a tendência de cada um",
  steps: "Mostre em etapas como instalar um sensor de umidade",
  funnel: "Faça o funil de inscrições: visitantes, cadastros, inscritos e concluintes",
  pyramid: "Monte a pirâmide de prioridades, do essencial ao desejável",
  list: "Liste os cinco cuidados antes de uma viagem longa",
  agenda: "Faça a agenda do evento com a parte atual destacada",
  timeline: "Faça a linha do tempo da história do cinema brasileiro",
  chart: "Faça um gráfico de linhas com a temperatura média de cada mês",
  table: "Monte a tabela comparando três planos, com o total destacado",
  map: "Mostre no mapa as estações de medição da planilha, coloridas pelo status, com um cartão ao clicar",
  compare: "Compare transporte público e carro próprio lado a lado",
  matrix: "Monte uma matriz 2x2 de esforço e impacto com as ideias do time",
  question: "Faça uma pergunta para a plateia com cronômetro de 30 segundos",
  poll: "Faça uma enquete ao vivo: qual tema vocês querem aprofundar?",
  image: "Ponha esta foto em tela cheia com uma legenda curta",
  code: "Mostre este código Python com as linhas da conexão destacadas",
  codewalk: "Explique este código uma linha por vez, com a saída simulada",
  api: "Faça uma chamada de API ao vivo que consulta o clima e mostra a resposta",
  spotlight: "Conduza o olhar pelas partes desta planta baixa, uma por vez",
  kinetic: "Faça a abertura com frases curtas aparecendo em ritmo, estilo tipografia cinética",
  video: "Ponha este vídeo do YouTube no slide",
  blocks: "Monte livremente um slide com título, dois textos e uma imagem em colunas",
  canvas: "Posicione o logotipo, o título e a foto onde eu indicar",
  references: "Liste as referências bibliográficas no fim",
  end: "Feche com um obrigado e os meus contatos",
};

export const LAYOUT_SAMPLES = {
  map: { layout: "map", kicker: "Monitoramento", title: "Estações de ==qualidade do ar==", basemap: "claro", layers: [
    { name: "Estações", color: "status", label: "nome", points: [
      { nome: "Centro", lat: -23.5489, lon: -46.6388, status: "Boa", pm25: 12 }, { nome: "Pinheiros", lat: -23.5614, lon: -46.7020, status: "Moderada", pm25: 24 },
      { nome: "Ibirapuera", lat: -23.5874, lon: -46.6576, status: "Boa", pm25: 9 }, { nome: "Mooca", lat: -23.5596, lon: -46.5996, status: "Ruim", pm25: 41 },
      { nome: "Santana", lat: -23.5027, lon: -46.6252, status: "Moderada", pm25: 27 }], colors: { Ruim: "alert" } }] },
  portal: portalExample,
  playground: playgroundExample,
  codelab: codeLabExample,
  graphlab: graphLabExample,
  mosaic: {layout:"mosaic",title:"Uma ideia, vários caminhos",items:[{title:"Descobrir",text:"Entenda o problema."},{title:"Experimentar",text:"Teste a hipótese."},{title:"Construir",text:"Transforme em produto."},{title:"Aprender",text:"Use o resultado para melhorar."},{title:"Compartilhar",text:"Mostre o que funcionou."}]},
  ribbon: {layout:"ribbon",title:"Do primeiro passo ao resultado",items:[{title:"Explorar",text:"Encontre uma oportunidade."},{title:"Testar",text:"Experimente em pequena escala."},{title:"Evoluir",text:"Repita o que funciona."}]},
  dossier: {layout:"dossier",title:"Referência rápida",items:[{title:"Requisição",text:"GET consulta o recurso.",code:"GET /exemplos/42"},{title:"Resposta",text:"Confira o status antes de usar o corpo.",code:'{"id":42,"status":"ok"}'}]},
  decisionlab: {layout:"decisionlab", title:"A revisão melhora o resultado?", lab:{volume:10000,errorRate:2,reviewRate:100,catchRate:60,introducedRate:0.2,seconds:30}},
  infographic: { layout: "infographic", shape: "arco", title: "Os ==desafios== do projeto", center: { title: "Desafios" }, items: [{ title: "Acesso", text: "Pedido pela Bridge" }, { title: "Dados", text: "Mockados no experimento" }, { title: "Segurança", text: "Chaves no Key Vault" }, { title: "Infra", text: "Namespace e firewall" }] },
  diagram: { layout: "diagram", kicker: "Processo", title: "Da ideia à ==produção==", mermaid: "flowchart LR\n  A([:lightbulb: Ideia]):::hi --> B{Vale testar?}\n  B -->|sim| C[:flask-conical: Experimento]\n  B -.->|não| X[Arquivar]:::vazado\n  C ==> D[:rocket: Produção]:::em" },
  solution: {layout:"solution", title:"Exercício: quanto rende em 3 anos?", problem:"R$ 1.000 aplicados a 1% ao mês, com juros compostos. Quanto há depois de 36 meses?", givens:[{symbol:"C", value:"1000", unit:"R\\$", label:"capital"}, {symbol:"i", value:"0,01", label:"taxa ao mês"}, {symbol:"n", value:"36", label:"meses"}], find:"M", steps:[{text:"Juros compostos", latex:"M = C\\,(1 + i)^n"}, {text:"Substitui os dados", latex:"M = 1000 \\cdot 1{,}01^{36}"}, {text:"Calcula a potência", latex:"1{,}01^{36} \\approx 1{,}4308"}], answer:{latex:"M \\approx R\\$\\,1.430{,}77", text:"Rende cerca de 43% em 3 anos."}},
  calc: {layout:"calc", title:"Qual é o regime do escoamento?", inputs:{V:{label:"Velocidade", latex:"V", value:1.5, min:0.01, max:4, step:0.01, unit:"m/s"}, D:{label:"Diâmetro", latex:"D", value:0.05, min:0.005, max:0.3, step:0.005, unit:"m"}, nu:{label:"Viscosidade (água, 20 °C)", latex:"\\nu = 1{,}0\\times10^{-6}\\ \\mathrm{m^2/s}", value:0.000001, fixed:true}}, outputs:[{name:"Re", label:"Número de Reynolds", latex:"Re = \\frac{VD}{\\nu}", fn:"V*D/nu", decimals:0}, {name:"regime", label:"Regime", of:"Re", cases:[{below:2300, text:"Laminar", color:"s3"}, {below:4000, text:"Transição", color:"em"}, {text:"Turbulento", color:"hi"}], scale:{min:100, max:1000000, log:true}}]},
  algo: {layout:"algo", title:"Bubble sort passo a passo", algorithm:"bubble", array:[5, 1, 4, 2, 8, 3]},
  carousel: {layout:"carousel", title:"Cinco lugares, cinco lições", style:"arc", items:[{title:"Montanha", text:"Subir devagar é o jeito mais rápido de chegar.", label:"Capítulo 1"}, {title:"Mar", text:"Tudo o que é fundo começa raso."}, {title:"Cidade", text:"Muita gente, muita luz, pouco silêncio."}, {title:"Deserto", text:"Onde o pouco vira muito."}, {title:"Floresta", text:"Cada árvore conta uma história."}]},
  duel: {layout:"duel", title:"Duelo de commits", file:"soma.js", base:"function soma(a, b) {\n  return a + b;\n}", people:["Ana","Beto"], bet:"Vai dar conflito?",
    turns:[{who:1, edit:{2:"  return a + b + 0;"}, commit:"ajusta soma"}, {who:2, edit:{2:"  return b + a;"}, commit:"inverte a ordem"}, {who:1, push:true}, {who:2, push:true}, {who:2, pull:true},
      {who:2, resolve:{2:"  return a + b;"}, commit:"resolve o conflito"}, {who:2, push:true}, {who:1, pull:true}]},
  terminals: {layout:"terminals", title:"Dois terminais", file:"README.md", base:"# Projeto\nversão 1", people:["Ana","Beto"],
    turns:[{who:1, edit:{2:"versão 2"}, commit:"sobe a versão"}, {who:1, push:true}, {who:2, pull:true}, {who:2, log:true}]},
  turns: {layout:"turns", title:"Code review ao vivo", people:[{name:"Ana", role:"autora do PR"}, {name:"Beto", role:"revisor"}],
    turns:[{who:1, text:"Abri o PR com a validação do Pix."}, {who:2, text:"Por que não usa o **schema** que já existe?", tag:"pergunta"}, {who:1, text:"Boa. Troquei e testei assim:", method:"POST", url:"/pix", status:201, code:'{ "valor": 10 }', language:"json"}, {who:2, text:"Aprovado.", tag:"aprovado"}]},
  science: {layout:"science", title:"Mexa no a e no b", equations:[{label:"A função",latex:"f(x) = a\\sin(bx)"},{label:"A derivada",latex:"f'(x) = ab\\cos(bx)"}], plot:{functions:["a*sin(b*x)","a*b*cos(b*x)"], x:[-6.3,6.3], params:{a:{value:1.5,min:0,max:3,label:"amplitude"},b:{value:1,min:0.5,max:3,label:"frequência"}}}},
  scenography: {layout:"scenography", scene:"stage", title:"ALÉM DO\nÓBVIO", kicker:"UMA NOVA PERSPECTIVA", subtitle:"Ideias que ocupam espaço.", tone:"dark", deco:"none"},
  cover: { layout: "cover", kicker: "Evento 2026", title: "Título da ==apresentação==", subtitle: "Um subtítulo curto", author: "Seu nome", figure: { icon: "rocket", size: 320 } },
  section: { layout: "section", number: 2, kicker: "Parte dois", title: "O problema" },
  statement: { layout: "statement", kicker: "A ideia", text: "Uma frase que ==muda tudo==." },
  calendar: { layout: "calendar", kicker: "Agenda", title: "Próximos lançamentos", events: [
    { date: "2026-11-12", title: "Beta aberto", tag: "Produto", text: "Para os 500 primeiros" }, { date: "2026-11-28", title: "Evento de lançamento", tag: "Evento" },
    { date: "2027-01-15", title: "Versão 2.0", tag: "Produto", text: "Com o app de celular" }], undated: [{ title: "Integração com o banco", text: "Em negociação" }] },
  poster: { layout: "poster", kicker: "Receita", title: "Pão de fermentação natural", subtitle: "Do fermento ao forno em quatro etapas", flow: true,
    panels: [
      { title: "Fermento", icon: "wheat", text: "Farinha e água, alimentados por 5 dias", facts: [{ value: "1:1", label: "farinha e água" }] },
      { title: "Massa", icon: "hand", text: "Misture e dobre a cada 30 min", facts: [{ value: "75%", label: "hidratação" }] },
      { title: "Descanso", icon: "thermometer", text: "Na geladeira, a massa ganha sabor", facts: [{ value: "12 h", label: "a 4 °C" }] },
      { title: "Forno", icon: "flame", text: "Panela tampada, depois sem tampa", facts: [{ value: "250 °C", label: "45 min" }] },
    ], key: "Tempos para uma cozinha a 24 °C." },
  definition: { layout: "definition", kicker: "O que é", term: "Hidrologia", origin: "do grego", parts: [{ word: "hydor", meaning: "água" }, { word: "logos", meaning: "ciência" }], text: "É a ciência que estuda ==a água sobre a Terra==: sua quantidade, distribuição e circulação, e sua relação com o meio ambiente e com os seres vivos.", icon: "droplet" },
  headline: { layout: "headline", text: "78% ==desistem==", caption: "no segundo passo" },
  quote: { layout: "quote", quote: "Dados vencem opiniões.", by: "Alguém sábio" },
  onepage: { layout: "onepage", title: "Cadastro digital", journey: [{ icon: "user", title: "Cliente chega", text: "Fila de 40 min" }, { icon: "file-text", title: "Preenche papel" }, { icon: "check", title: "Conta aberta", text: "Até 5 dias" }], problem: { text: "Cadastro em papel atrasa a abertura de contas", numbers: [{ value: "5 dias", label: "para abrir uma conta" }] }, solution: { text: "Cadastro no tablet, com assinatura digital", items: ["Conta aberta no mesmo dia"] } },
  status: { layout: "status", kicker: "Semana 39", title: "Portal do cliente", health: "risco", progress: 65, done: ["Tela de login", "Integração com o cadastro"], doing: ["Recuperação de senha"], blocked: [{ text: "Liberação de firewall", owner: "Infra", due: "30/09" }], upcoming: ["Homologar com o negócio"] },
  hub: { layout: "hub", title: "Qual é o seu caso?", question: "Cada caminho tem o seu prazo", options: [{ icon: "flask-conical", title: "Experimento", meta: "30 dias", goto: "exp" }, { icon: "rocket", title: "Projeto", meta: "DEV, HOM e PROD", goto: "proj" }] },
  number: { layout: "number", value: 42, suffix: "%", label: "mais rápido" },
  split: { layout: "split", title: "Texto e figura", bullets: ["Primeiro ponto", "Segundo ponto"], figure: { icon: "lightbulb", size: 300 } },
  full: { layout: "full", figure: { chart: "donut", value: 72, center: "72%" }, title: "Figura em página inteira", overlay: "left" },
  cards: { layout: "cards", title: "Três pilares", items: [{ icon: "shield", title: "Seguro" }, { icon: "zap", title: "Rápido" }, { icon: "heart", title: "Simples" }] },
  bento: { layout: "bento", title: "Em um olhar", tiles: [{ value: "8,4 mi", title: "Receita", hl: true }, { icon: "users", title: "NPS 91" }, { icon: "rocket", title: "3 lançamentos" }, { icon: "globe", title: "2 países" }, { icon: "check", title: "Zero falhas" }] },
  stats: { layout: "stats", title: "Resultados", stats: [{ value: "+42%", label: "Receita" }, { value: "0,6%", label: "Churn" }, { value: "91", label: "NPS" }] },
  steps: { layout: "steps", title: "Como funciona", steps: [{ title: "Coletar" }, { title: "Analisar" }, { title: "Agir" }] },
  funnel: { layout: "funnel", title: "Funil", stages: [{ title: "Visitas", value: "120k" }, { title: "Cadastro", value: "18k" }, { title: "Pagantes", value: "900" }] },
  pyramid: { layout: "pyramid", title: "Pirâmide", levels: [{ title: "Topo" }, { title: "Meio" }, { title: "Base" }] },
  list: { layout: "list", title: "Lista", items: ["Primeiro item", "Segundo item", "Terceiro item"] },
  agenda: { layout: "agenda", title: "Agenda", current: 2, items: [{ title: "Abertura" }, { title: "O problema" }, { title: "A solução" }] },
  timeline: { layout: "timeline", title: "Linha do tempo", events: [{ when: "2019", title: "Início" }, { when: "2022", title: "Virada" }, { when: "2026", title: "Hoje" }] },
  table: { layout: "table", title: "Vazões máximas anuais", head: ["Ano", "Vazão (m³/s)", "Ordem", "TR (anos)"], rows: [["1984", "2.218,0", "1", "9,0"], ["1985", "1.980,5", "2", "4,5"], ["1986", "1.712,3", "3", "3,0"], ["1987", "1.445,0", "4", "2,3"]], highlight: { row: 1 }, side: "A maior cheia do período tem ==TR de 9 anos==.", source: "Posto fluviométrico (exemplo)" },
  chart: { layout: "chart", title: "Crescimento", chart: { chart: "column", data: [{ label: "A", value: 30 }, { label: "B", value: 55 }, { label: "C", value: 80 }] }, side: "Subiu ==2,6×==" },
  compare: { layout: "compare", title: "Antes × depois", left: { label: "Antes", value: "3 dias" }, right: { label: "Depois", value: "2 h", hl: true } },
  matrix: { layout: "matrix", title: "Matriz", x: ["Fácil", "Difícil"], y: ["Alto impacto", "Baixo impacto"], cells: [{ title: "Faça já", hl: true }, { title: "Planeje" }, { title: "Delegue" }, { title: "Evite" }] },
  question: { layout: "question", question: "Qual você escolheria?", options: ["Opção A", "Opção B", "Opção C"], timer: 30 },
  poll: { layout: "poll", question: "Vote agora", id: "exemplo", options: ["Sim", "Não", "Talvez"] },
  image: { layout: "image", figure: { picto: "scene", name: "desk" }, title: "Imagem em tela cheia" },
  code: { layout: "code", title: "Código", filename: "exemplo.py", language: "Python", code: "def ola():\n    return 'mundo'", highlight: [2] },
  codewalk: { layout: "codewalk", kicker: "Laboratório · API", title: "Uma API em ==três movimentos==", filename: "primeira-api.js", language: "JavaScript",
    code: "const resposta = await fetch('/api/aulas');\n\nconst aulas = await resposta.json();\n\nconst ativas = aulas.filter(aula => aula.ativa);\n\nconsole.log(ativas.length);",
    steps: [{ title: "Faça a pergunta", text: "fetch envia o pedido. await dá tempo para a resposta chegar.", highlight: [1], output: "GET /api/aulas → 200 OK" },
      { title: "Transforme a resposta", text: "O corpo JSON vira uma lista que o código consegue usar.", highlight: [3], output: "[{ id: 1, ativa: true },\n { id: 2, ativa: false }]" },
      { title: "Escolha o que importa", text: "Só as aulas ativas passam pelo filtro. Qual será a saída?", highlight: [5, 7], output: "1" }] },
  spotlight: { layout: "spotlight", kicker: "Olhar de quem programa", title: "O detalhe que ==muda tudo==", caption: "Inspeção de uma resposta HTTP · clique nos detalhes para explorar",
    figure: { svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 600"><rect width="1000" height="600" fill="#101725"/><rect width="1000" height="70" fill="#1d273a"/><circle cx="30" cy="35" r="7" fill="#f09282"/><circle cx="55" cy="35" r="7" fill="#e5bd76"/><circle cx="80" cy="35" r="7" fill="#93c1a4"/><g font-family="monospace"><text x="125" y="44" font-size="22" fill="#a1adc4">API EXPLORER / aulas</text><rect x="40" y="110" width="920" height="84" rx="10" fill="#263348"/><text x="66" y="162" font-size="28" fill="#9ce3c3">GET</text><text x="145" y="162" font-size="28" fill="#e8edf5">/api/aulas</text><rect x="40" y="230" width="920" height="56" rx="8" fill="#142d2a"/><text x="65" y="267" font-size="24" fill="#9ce3c3">200 OK</text><text x="780" y="267" font-size="22" fill="#9ce3c3">42 ms</text><text x="55" y="341" font-size="25" fill="#c0cee9">{</text><text x="90" y="390" font-size="25" fill="#9fc3ff">"aulas": [</text><text x="125" y="439" font-size="25" fill="#e8edf5">{ "id": 1, "ativa": true }</text><text x="90" y="488" font-size="25" fill="#9fc3ff">]</text><text x="55" y="537" font-size="25" fill="#c0cee9">}</text></g></svg>' },
    hotspots: [{ x: 4, y: 18, width: 92, height: 15, title: "O pedido", text: "O verbo GET consulta o recurso. A rota identifica a coleção de aulas." },
      { x: 4, y: 38, width: 92, height: 10, title: "A confirmação", text: "200 OK confirma o sucesso. O tempo ajuda a investigar a experiência do usuário." },
      { x: 5, y: 52, width: 78, height: 39, title: "Os dados", text: "A estrutura JSON é o contrato que o front-end precisa entender." }] },
  kinetic: { layout: "kinetic", figure: { svg: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1920 1080"><defs><linearGradient id="stage" x2="0" y2="1"><stop stop-color="#697a78"/><stop offset="1" stop-color="#26353a"/></linearGradient><linearGradient id="window" x2="0" y2="1"><stop stop-color="#e1cba1"/><stop offset="1" stop-color="#8d9990"/></linearGradient></defs><path fill="url(#stage)" d="M0 0h1920v1080H0z"/><path fill="#202b2e" d="M0 0h430v1080H0zM1490 0h430v1080h-430z"/><path fill="url(#window)" d="M500 90h910v660H500z"/><path fill="#d0b88e" opacity=".4" d="M500 560h910v190H500z"/><path fill="#293432" d="M0 850h1920v230H0z"/><path fill="#394342" d="M720 814h480v36H720z"/><path fill="#26302f" d="M836 555c28-120 205-154 266-14l76 263H760z"/><circle cx="960" cy="465" r="74" fill="#39403b"/></svg>' }, autoplay: true, interval: 1800,
    beats: [{ text: "Uma ideia", style: "clean", position: "left", color: "white", size: "medium", tag: "GANHA FORMA" },
      { text: "muda o olhar", style: "clean", position: "right", color: "gold", size: "medium" },
      { text: "e abre caminhos", style: "clean", position: "left", color: "white", size: "medium" }] },
  // genérico de propósito: troque método, URL e corpo pelos do seu serviço (os exemplos prontos ficam no deck "Exemplo: aula de APIs")
  api: { layout: "api", kicker: "Ao vivo", title: "Minha ==chamada==", text: "Troque o método, a URL e o corpo pelos do seu serviço", request: { method: "POST", url: "{{base}}/echo", body: { mensagem: "Olá, API" } }, answer: "$.recebido.mensagem" },
  video: { layout: "video", title: "Assista", url: "https://example.com", label: "Assistir" },
  blocks: { layout: "blocks", title: "Blocos livres", content: [{ row: [{ lead: "Esquerda" }, { lead: "Direita" }] }] },
  canvas: { layout: "canvas", elements: [{ h2: "Livre", x: 200, y: 200 }, { icon: "star", size: 200, x: 1200, y: 400 }] },
  references: { layout: "references", title: "Fontes", items: ["Autor (2024). Título.", "Outro (2025). Estudo."] },
  end: { layout: "end", title: "Obrigado.", subtitle: "Perguntas?", contacts: ["seu@email.com"] },
};
