import test from 'node:test';import assert from 'node:assert/strict';import {el} from '../src/elements.js';
// Animação sob carga não anda no ritmo de um relógio fixo: espera a condição de verdade (o quadro mudou; o quadro
// parou de mudar), com prazo, em vez de comparar depois de 100–300 ms.
async function changes(read,ms=5000){const a=await read(),end=Date.now()+ms;while(Date.now()<end){await new Promise(r=>setTimeout(r,60));if(await read()!==a)return true;}return false;}
async function settles(read,ms=5000){const end=Date.now()+ms;let a=await read();while(Date.now()<end){await new Promise(r=>setTimeout(r,250));const b=await read();if(b===a)return true;a=b;}return false;}
test('cenas de movimento são elementos declarativos portáteis e isolados',()=>{for(const type of ['wireframe','requests','flow','chat','terminal']){const html=el({motion:{type,user:'Olá </script>',assistant:'Resposta'},x:120,y:80,w:400,h:220});assert.match(html,/data-motion/);assert.match(html,/sandbox="allow-scripts"/);assert.match(html,/left:120px/);assert.match(html,/srcdoc=/);}});
test('cena holográfica aceita camadas em perspectiva, paleta e transparência sem mídia externa',async t=>{
 const browser=await browserOrSkip(t);if(!browser)return;const deck=tempDeck();
 try{const file=deck.file+'.html';fs.writeFileSync(file,buildHTML({theme:'prisma',slides:[{layout:'canvas',elements:[{motion:{type:'hologram',background:'transparent',foreground:'accent',secondary:'c3',layers:[{shape:'cube',x:.3,y:.5,scale:.18},{shape:'sphere',x:.7,y:.45,scale:.2}]},x:0,y:0,w:1920,h:1080}]},{layout:'section',title:'Próximo'}]}).html);const {page,errors}=await newPage(browser);await page.goto(pathToFileURL(file).href);const canvas=page.frameLocator('iframe[data-motion=hologram]').locator('canvas');await canvas.waitFor();const frameOf=()=>canvas.evaluate(e=>e.toDataURL());assert.ok(await changes(frameOf),'o holograma anima');await page.evaluate(()=>window.sagadeck.goto(1));assert.ok(await settles(frameOf),'fora do slide, a animação para');assert.equal(await page.frameLocator('iframe[data-motion=hologram]').locator('body').evaluate(e=>getComputedStyle(e).color),'rgb(55, 105, 232)');assert.deepEqual(errors,[]);}
 finally{await browser.close();deck.cleanup();}
});
import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {buildHTML} from '../src/build.js';import {browserOrSkip,newPage,tempDeck} from './helpers.js';
test('captura com movimento reduzido mostra terminal completo, não digitação parcial',async t=>{
 const browser=await browserOrSkip(t);if(!browser)return;const deck=tempDeck();
 try{const file=path.join(deck.dir,'poster.html');fs.writeFileSync(file,buildHTML({motion:'none',slides:[{layout:'canvas',elements:[{motion:{type:'terminal',lines:['first line','complete final line'],typing:.2},x:100,y:100,w:600,h:300}]}]}).html);const {page,errors}=await newPage(browser);await page.goto(pathToFileURL(file).href);const feed=page.frameLocator('iframe[data-motion=terminal]').locator('.feed');await feed.filter({hasText:'first'}).waitFor();assert.equal(await feed.innerText(),'first line\ncomplete final line','no instante em que aparece, já está completo (digitando, estaria pela metade)');assert.deepEqual(errors,[]);
 }finally{await browser.close();deck.cleanup();}
});
test('terminal nativo digita roteiro fornecido e pausa fora do slide',async t=>{
 const browser=await browserOrSkip(t);if(!browser)return;const deck=tempDeck();
 try{const file=path.join(deck.dir,'terminal.html');fs.writeFileSync(file,buildHTML({slides:[{layout:'canvas',elements:[{motion:{type:'terminal',lines:['load("document")','connect("services")'],typing:.05,speed:1},x:100,y:100,w:600,h:300}]},{layout:'section',title:'Próximo'}]}).html);const {page,errors}=await newPage(browser);await page.goto(pathToFileURL(file).href);const feed=page.frameLocator('iframe[data-motion=terminal]').locator('.feed');await feed.filter({hasText:'load'}).waitFor();await feed.filter({hasText:'connect'}).waitFor();await page.evaluate(()=>window.sagadeck.goto(1));assert.ok(await settles(()=>feed.innerText()),'fora do slide, o terminal para');assert.deepEqual(errors,[]);
 }finally{await browser.close();deck.cleanup();}
});
test('mini movimento tem região reservada e não sobrepõe conteúdo nem rodapé',async t=>{
 const browser=await browserOrSkip(t);if(!browser)return;const deck=tempDeck();
 try{const file=path.join(deck.dir,'accent.html');fs.writeFileSync(file,buildHTML({footer:{left:'Evento',right:'{n}'},slides:[{layout:'statement',footer:true,text:'Conteúdo',motionAccent:{type:'requests',speed:4}}]}).html);const {page,errors}=await newPage(browser);await page.goto(pathToFileURL(file).href);
 const regions=await page.evaluate(()=>{const r=s=>{const b=document.querySelector(s).getBoundingClientRect();return {top:b.top,bottom:b.bottom}};return {safe:r('.safe'),accent:r('.motion-accent'),footer:r('.foot')}});
   assert.ok(regions.safe.bottom<regions.accent.top);assert.ok(regions.accent.bottom<regions.footer.top);assert.equal(await page.locator('iframe[data-motion=requests]').count(),1);const iframe=await page.locator('iframe[data-motion=requests]').boundingBox();const accent=await page.locator('.motion-accent').boundingBox();assert.ok(iframe.y+iframe.height<=accent.y+accent.height+1,'a cena inteira cabe na região reservada');const frame=page.frameLocator('iframe[data-motion=requests]');assert.equal(await frame.locator('body').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)','detalhe integrado não traz retângulo opaco');assert.deepEqual(errors,[]);
 }finally{await browser.close();deck.cleanup();}
});
test('chat manual digita no campo, envia, pensa e avança sem botões na plateia',async t=>{const browser=await browserOrSkip(t);if(!browser)return;const deck=tempDeck();try{const file=path.join(deck.dir,'motion.html');fs.writeFileSync(file,buildHTML({slides:[{layout:'canvas',elements:[{motion:{type:'chat',user:'Teste',assistant:'Resposta',recognition:.1,thinking:1.5,typing:.06,read:1,finish:'next'},x:100,y:100,w:500,h:350}]},{layout:'canvas',elements:[{motion:{type:'requests',speed:4},x:0,y:0,w:500,h:250}]}]}).html);const {page,errors}=await newPage(browser);await page.goto(pathToFileURL(file).href);const f=page.frameLocator('iframe[data-motion=chat]');await f.locator('main').waitFor();assert.equal(await f.locator('.chat').isVisible(),false);await page.keyboard.press('Space');await f.locator('.input').filter({hasText:'Te'}).waitFor();assert.equal(await f.locator('.bubble').count(),0);await f.locator('.status').filter({hasText:'Pensando'}).waitFor();assert.equal(await f.locator('.user').textContent(),'Teste');assert.equal(await f.locator('.input').textContent(),'');await page.waitForFunction(()=>window.sagadeck.cur===1);const request=page.frameLocator('iframe[data-motion=requests]');assert.ok(await changes(()=>request.locator('.feed').innerText()),'os pedidos seguem chegando');assert.deepEqual(errors,[]);}finally{await browser.close();deck.cleanup();}});

test('chat termina iniciando o vídeo manual no mesmo slide',async t=>{const browser=await browserOrSkip(t);if(!browser)return;const deck=tempDeck();try{fs.copyFileSync(path.resolve('test/fixtures/short.mp4'),path.join(deck.dir,'clip.mp4'));const file=path.join(deck.dir,'handoff.html');fs.writeFileSync(file,buildHTML({_dir:deck.dir,slides:[{layout:'canvas',elements:[{video:'clip.mp4',start:'manual',finish:'next',controls:'stage',x:0,y:0,w:1920,h:1080},{motion:{type:'chat',user:'U',assistant:'A',recognition:.05,thinking:.05,typing:.01,read:.05,finish:'video'},x:900,y:600,w:450,h:300}]},{layout:'section',title:'Final'}]}).html);const {page,errors}=await newPage(browser);await page.goto(pathToFileURL(file).href);await page.frameLocator('iframe[data-motion=chat]').locator('main').waitFor();await page.waitForFunction(()=>document.querySelector('video').readyState>=3);assert.equal(await page.locator('video').evaluate(v=>v.paused),true);await page.keyboard.press('Space');await page.waitForFunction(()=>document.querySelector('iframe[data-motion=chat]').style.visibility==='hidden');await page.waitForFunction(()=>window.sagadeck.cur===1);assert.deepEqual(errors,[]);}finally{await browser.close();deck.cleanup();}});
// Deck com motion: none: a cena nasce parada (sabe pelo próprio documento). Antes só sabia pela mensagem da página,
// que sob carga chegava depois de o terminal começar a digitar ("first l_" na captura).
test('motion: none chega à cena já no documento dela (não depende da mensagem da página)',()=>{
 const doc=(motion)=>buildHTML({...(motion?{motion}:{}),slides:[{layout:'canvas',elements:[{motion:{type:'terminal',lines:['a']},x:0,y:0,w:600,h:300}]}]}).html;
 assert.match(doc('none'),/&quot;still&quot;:true/);
 assert.doesNotMatch(doc(null),/&quot;still&quot;/);
});
