import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {pathToFileURL} from 'node:url';import {buildHTML} from '../src/build.js';import {motionOptions} from '../src/motion.js';import {browserOrSkip,newPage,tempDeck} from './helpers.js';
test('trace segue caminho vertical transparente, anima e pausa fora do slide sem JS externo',async t=>{
 const browser=await browserOrSkip(t);if(!browser)return;const deck=tempDeck();
 try{const file=deck.file+'.html';fs.writeFileSync(file,buildHTML({slides:[{layout:'canvas',elements:[{motion:{type:'trace',background:'transparent',path:[[.5,.05],[.5,.95]],foreground:'accent',accent:'c3',speed:1},x:800,y:100,w:60,h:800}]},{layout:'section',title:'Próximo'}]}).html);const{page,errors}=await newPage(browser);await page.goto(pathToFileURL(file).href);const canvas=page.frameLocator('iframe[data-motion=trace]').locator('canvas');await canvas.waitFor();await page.waitForTimeout(100);const a=await canvas.evaluate(e=>e.toDataURL());await page.waitForTimeout(150);assert.notEqual(await canvas.evaluate(e=>e.toDataURL()),a);const bounds=await canvas.evaluate(e=>{const d=e.getContext('2d').getImageData(0,0,e.width,e.height).data;let min=e.width,max=0;for(let y=0;y<e.height;y++)for(let x=0;x<e.width;x++)if(d[(y*e.width+x)*4+3]){min=Math.min(min,x);max=Math.max(max,x);}return{min,max,w:e.width};});assert.ok(bounds.max-bounds.min<bounds.w*.2,'movimento vertical não desenha um mini fluxo horizontal');await page.evaluate(()=>window.sagadeck.goto(1));await page.waitForTimeout(100);const paused=await canvas.evaluate(e=>e.toDataURL());await page.waitForTimeout(150);assert.equal(await canvas.evaluate(e=>e.toDataURL()),paused);assert.equal(await page.frameLocator('iframe[data-motion=trace]').locator('body').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');assert.deepEqual(errors,[]);}
 finally{await browser.close();deck.cleanup();}
});
test('trace limita pontos, normaliza coordenadas e tem caminho útil mesmo sem configuração',()=>{
 const o=motionOptions({type:'trace',path:Array.from({length:100},()=>[-2,4]),pulses:100});assert.equal(o.path.length,64);assert.deepEqual(o.path[0],[0,1]);assert.equal(o.pulses,8);assert.equal(motionOptions({type:'trace'}).path.length,2);
});
