import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {pathToFileURL} from 'node:url';import {buildHTML} from '../src/build.js';import {motionOptions} from '../src/motion.js';import {browserOrSkip,newPage,tempDeck,motionDiag} from './helpers.js';
// espera a condição de verdade (o quadro mudou; parou de mudar), com prazo, em vez de comparar depois de 100–150 ms
async function changes(read,ms=5000){const a=await read(),end=Date.now()+ms;while(Date.now()<end){await new Promise(r=>setTimeout(r,60));if(await read()!==a)return true;}return false;}
async function settles(read,ms=5000){const end=Date.now()+ms;let a=await read();while(Date.now()<end){await new Promise(r=>setTimeout(r,250));const b=await read();if(b===a)return true;a=b;}return false;}
test('trace segue caminho vertical transparente, anima e pausa fora do slide sem JS externo',async t=>{
 const browser=await browserOrSkip(t);if(!browser)return;const deck=tempDeck();
 try{const file=deck.file+'.html';fs.writeFileSync(file,buildHTML({slides:[{layout:'canvas',elements:[{motion:{type:'trace',background:'transparent',path:[[.5,.05],[.5,.95]],foreground:'accent',accent:'c3',speed:1},x:800,y:100,w:60,h:800}]},{layout:'section',title:'Próximo'}]}).html);const{page,errors}=await newPage(browser);await page.goto(pathToFileURL(file).href);const canvas=page.frameLocator('iframe[data-motion=trace]').locator('canvas');await canvas.waitFor();const frameOf=()=>canvas.evaluate(e=>e.toDataURL());assert.ok(await changes(frameOf),'o trace anima '+await motionDiag(page,'trace'));const bounds=await canvas.evaluate(e=>{const d=e.getContext('2d').getImageData(0,0,e.width,e.height).data;let min=e.width,max=0;for(let y=0;y<e.height;y++)for(let x=0;x<e.width;x++)if(d[(y*e.width+x)*4+3]){min=Math.min(min,x);max=Math.max(max,x);}return{min,max,w:e.width};});assert.ok(bounds.max-bounds.min<bounds.w*.2,'movimento vertical não desenha um mini fluxo horizontal');await page.evaluate(()=>window.sagadeck.goto(1));assert.ok(await settles(frameOf),'fora do slide, o trace para');assert.equal(await page.frameLocator('iframe[data-motion=trace]').locator('body').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');assert.deepEqual(errors,[]);}
 finally{await browser.close();deck.cleanup();}
});
test('trace limita pontos, normaliza coordenadas e tem caminho útil mesmo sem configuração',()=>{
 const o=motionOptions({type:'trace',path:Array.from({length:100},()=>[-2,4]),pulses:100});assert.equal(o.path.length,64);assert.deepEqual(o.path[0],[0,1]);assert.equal(o.pulses,8);assert.equal(motionOptions({type:'trace'}).path.length,2);
});
