import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import YAML from "yaml";
import { browserOrSkip, newPage, startStudio, tempDeck } from "./helpers.js";

test("screenshot: criar destaques visualmente, editar, cancelar e distribuir", async t => {
  const browser = await browserOrSkip(t); if (!browser) return;
  const temp = tempDeck(), studio = await startStudio(temp.file);
  try {
    const { page, errors } = await newPage(browser, studio.url);
    const saved = () => YAML.parse(fs.readFileSync(temp.file, "utf8"));
    // a gravação é assíncrona (no CI, lenta): espera o arquivo chegar lá em vez de um tempo fixo
    const until = async (ok) => { for (let i = 0; i < 50 && !ok(); i++) await page.waitForTimeout(100); return ok(); };
    const n = saved().slides.length;
    const fixture = await browser.newPage({ viewport: { width: 960, height: 600 } });
    await fixture.setContent('<body style="background:#eef2f7;font:24px Arial;padding:50px"><h1>Portal de demonstração</h1><p>Selecione o workflow</p><button style="background:#7352c7;color:white;padding:20px">Executar</button></body>');
    const png = await fixture.screenshot(); await fixture.close();
    await page.click("#btn-screenshot");
    await page.locator(".shot-dialog [data-input]").setInputFiles({ name: "portal.png", mimeType: "image/png", buffer: png });
    await page.waitForFunction(() => document.querySelector('.shot-image-wrap img')?.naturalWidth === 960);
    await page.locator(".shot-dialog [data-title]").fill("Configure o workflow");
    const wrap = page.locator(".shot-image-wrap"), r = await wrap.boundingBox();
    await page.mouse.click(r.x + r.width * .3, r.y + r.height * .4);
    await page.locator("[data-label]").fill("Escolha o workflow");
    await page.locator("[data-text]").fill("Selecione a configuração que será executada.");
    await page.click('[data-mode="area"]');
    await page.mouse.move(r.x + r.width * .5, r.y + r.height * .5);
    await page.mouse.down(); await page.mouse.move(r.x + r.width * .8, r.y + r.height * .75); await page.mouse.up();
    await page.locator("[data-label]").fill("Execute");
    await page.click("[data-up]");
    await page.click("[data-apply]");
    await page.waitForFunction(() => !document.querySelector(".shot-dialog"));
    await until(() => saved().slides.length === n + 1 && saved().slides[1].hotspots?.length === 2);
    let slide = saved().slides[1];
    assert.equal(saved().slides.length, n + 1);
    assert.equal(slide.layout, "spotlight");
    assert.match(slide.image, /^data:image\/png;base64,/);
    assert.equal(slide.hotspots[0].title, "Execute");
    assert.equal(slide.hotspots[1].kind, "point");
    assert.ok(Math.abs(slide.hotspots[1].x - 30) < 1);
    assert.ok(Math.abs(slide.hotspots[0].width - 30) < 1);
    await page.getByRole("button", { name: "Editar imagem e destaques", exact: true }).click();
    await page.locator(".shot-dialog [data-title]").fill("Não salvar");
    await page.click("[data-cancel]");
    assert.equal(saved().slides[1].title, "Configure o workflow");
    await page.getByRole("button", { name: "Editar imagem e destaques", exact: true }).click();
    // o destaque só aparece quando a imagem termina de carregar (antes a área fica escondida e o foco não pega;
    // o focus() não espera ficar visível, e no CI a imagem demora mais)
    await page.locator('.shot-mark.point').waitFor({ state: "visible" });
    await page.locator('.shot-mark.point').focus();
    await page.keyboard.press("ArrowRight");
    await page.click("[data-apply]");
    assert.ok(await until(() => saved().slides[1].hotspots[1].x > slide.hotspots[1].x));
    const preview = await browser.newPage();
    await preview.goto(studio.url + "/preview?export=1");
    await preview.waitForFunction(() => window.sagadeck);
    await preview.evaluate(() => window.sagadeck.goto(1, 0));
    assert.equal(await preview.locator('[data-idx="1"] .lesson-summary').isVisible(), true);
    assert.match(await preview.locator('[data-idx="1"] .lesson-summary').innerText(), /Escolha o workflow/);
    await preview.close();
    await page.getByRole("button", { name: "Editar imagem e destaques", exact: true }).click();
    await page.locator('.shot-mark.point').click();
    await page.locator('[data-label]').fill('Texto');
    await page.keyboard.press('Backspace');
    assert.equal(await page.locator('[data-label]').inputValue(), 'Text');
    assert.equal(await page.locator('.shot-mark').count(), 2, 'Backspace no campo não remove destaque');
    await page.locator('.shot-mark.point').click();
    await page.keyboard.press('Delete');
    assert.equal(await page.locator('.shot-mark').count(), 1, 'Delete remove o ponto clicado');
    assert.equal(await page.locator('.shot-mark.area').textContent(), '1', 'renumera os destaques');
    await page.locator('.shot-mark.area').click();
    await page.keyboard.press('Backspace');
    assert.equal(await page.locator('.shot-mark').count(), 0, 'Backspace remove a área clicada');
    await page.keyboard.press('Delete');
    await page.click('[data-apply]');
    await until(() => !saved().slides[1].hotspots?.length);
    assert.equal(saved().slides[1].hotspots.length, 0, 'exclusão persiste no arquivo');
    assert.equal(saved().slides[1].layout, 'image');
    const base64 = png.toString("base64");
    for (const type of ["paste", "drop"]) {
      await page.evaluate(({ type, base64 }) => {
        const bytes = Uint8Array.from(atob(base64), c => c.charCodeAt(0));
        const dt = new DataTransfer(); dt.items.add(new File([bytes], "colada.png", { type: "image/png" }));
        if (type === "paste") document.body.dispatchEvent(new ClipboardEvent("paste", { bubbles: true, cancelable: true, clipboardData: dt }));
        else document.body.dispatchEvent(new DragEvent("drop", { bubbles: true, cancelable: true, dataTransfer: dt }));
      }, { type, base64 });
      await page.waitForFunction(() => document.querySelector('.shot-image-wrap img')?.naturalWidth === 960);
      await page.click("[data-cancel]");
      assert.equal(saved().slides.length, n + 1, `${type}: cancelar não insere cena`);
    }
    await page.click("#btn-screenshot");
    await page.locator(".shot-dialog [data-input]").setInputFiles({ name: "estatica.png", mimeType: "image/png", buffer: png });
    await page.waitForFunction(() => document.querySelector('.shot-image-wrap img')?.naturalWidth === 960);
    await page.click("[data-apply]");
    await until(() => saved().slides[2]?.layout === "image");
    assert.equal(saved().slides[2].layout, "image", "imagem sem destaques continua estática");
    assert.equal(saved().slides[2].fit, "contain", "não corta o screenshot");
    await page.setViewportSize({ width: 390, height: 844 });
    await page.click("#btn-screenshot");
    assert.ok(await page.locator(".shot-dialog").isVisible());
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.click("[data-cancel]");
    assert.deepEqual(errors, []);
  } finally { await browser.close(); await studio.close(); temp.cleanup(); }
});
