(()=>{
 for(const root of document.querySelectorAll('[data-meeting]')){
  let state=JSON.parse(root.querySelector('.meeting-state').textContent),confirmed=structuredClone(state),timer,chain=Promise.resolve();const votes=[...root.querySelectorAll('[data-vote]')],abstain=root.querySelector('[data-abstain]'),status=root.querySelector('[data-meeting-status]');
  const read=()=>({id:root.dataset.meeting,votes:votes.map(e=>Number(e.value)),abstentions:Number(abstain.value),approved:!!state.approved});
  function paint(){const b=read(),total=b.votes.reduce((a,v)=>a+v,0),max=Math.max(...b.votes),winners=b.votes.flatMap((n,i)=>n===max?[i]:[]);votes.forEach((e,i)=>{e.closest('label').querySelector('i').style.width=(total?100*b.votes[i]/total:0)+'%';e.disabled=!!state.approved});abstain.disabled=!!state.approved;root.querySelector('[data-meeting-approve]').disabled=state.approved||max===0||winners.length!==1;status.textContent=state.approved?'Decisão aprovada · '+votes[state.selected]?.getAttribute('aria-label').replace('Votos: ',''):total+' votos + '+b.abstentions+' abstenções · '+(max===0?'Aguardando votos':winners.length>1?'Empate; decisão aberta':'Resultado provisório');}
  function save(){const b=read();chain=chain.then(async()=>{if(location.protocol==='file:'){status.textContent='Para salvar decisões na apresentação, abra pelo Studio.';return;}try{const r=await fetch('/api/meeting',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}),data=await r.json();if(!r.ok)throw Error(data.error);state=data.decision;confirmed=structuredClone(state);if(Number.isFinite(data.value))for(const e of document.querySelectorAll("[data-decision-input]"))if(e.dataset.decisionInput===b.id){e.value=data.value;e.dispatchEvent(new Event("input",{bubbles:true}))}paint();}catch(e){state=structuredClone(confirmed);paint();status.textContent='Não foi salvo: '+e.message;}});}
  root.addEventListener('keydown',e=>e.stopPropagation());root.addEventListener('input',()=>{state.approved=false;paint();clearTimeout(timer);timer=setTimeout(save,300)});
  root.querySelector('[data-meeting-approve]').onclick=()=>{clearTimeout(timer);const b=read(),max=Math.max(...b.votes);state={...state,approved:true,selected:b.votes.indexOf(max)};save()};root.querySelector('[data-meeting-reopen]').onclick=()=>{state.approved=false;state.selected=null;paint();save()};paint();
 }
})();
