import {esc} from './markup.js';
import {playgroundDocument} from './playground.js';
import {drawHologram} from './hologram.js';
const number=(x,f,min,max)=>Math.min(max,Math.max(min,Number.isFinite(Number(x))?Number(x):f));
const color=(x,f)=>/^#?[0-9a-f]{6}$/i.test(x||'')?'#'+String(x).replace('#',''):f;
export function motionOptions(value,colors={}){
 const o=typeof value==='string'?{type:value}:value||{};
 if(!['wireframe','hologram','trace','requests','flow','chat','terminal'].includes(o.type))throw new Error('motion.type: wireframe, hologram, trace, requests, flow, chat ou terminal.');
 const aliases={fg:'ink',bg:'paper',hi:'accent',em:'alert'};
 const resolved=(v,f)=>color(colors[aliases[v]||v]||v,f);
 const trace=(Array.isArray(o.path)&&o.path.length>=2?o.path:[[.05,.5],[.95,.5]]).slice(0,64).map(p=>[number(Array.isArray(p)?p[0]:p?.x,0,0,1),number(Array.isArray(p)?p[1]:p?.y,0,0,1)]);
 const transparent=o.background==='transparent';
 const layers=(Array.isArray(o.layers)&&o.layers.length?o.layers:[{shape:o.shape,x:.5,y:.5,scale:.24}]).slice(0,6).map(l=>({shape:['sphere','cube','plane','ring'].includes(l.shape)?l.shape:'sphere',x:number(l.x,.5,-.5,1.5),y:number(l.y,.5,-.5,1.5),scale:number(l.scale,.24,.03,1),speed:number(l.speed,1,.1,4),rotation:number(l.rotation,0,-10,10)}));
 return {type:o.type,path:trace,closed:o.closed===true,pulses:Math.round(number(o.pulses,2,1,8)),lineWidth:number(o.lineWidth,1.2,.5,6),layers,opacity:number(o.opacity,.7,.05,1),lines:Array.isArray(o.lines)?o.lines.map(String):String(o.code||'').split('\n'),fontSize:number(o.fontSize,16,10,40),shape:o.shape==='cube'?'cube':'sphere',speed:number(o.speed,1,.1,8),recognition:number(o.recognition,1,0,10),thinking:number(o.thinking,.8,0,10),read:number(o.read,2,0,15),typing:number(o.typing,.035,.01,.2),caption:String(o.caption||''),user:String(o.user||''),assistant:String(o.assistant||''),background:transparent?'transparent':resolved(o.background,'#111e30'),foreground:resolved(o.foreground,transparent?color(colors.ink,'#182642'):'#b5c9db'),accent:resolved(o.accent,color(colors.alert,'#cc092f')),secondary:resolved(o.secondary,transparent?color(colors.accent,'#3769e8'):'#aa9ccf'),manual:o.start!=='auto',finish:['next','video','hold'].includes(o.finish)?o.finish:'hold'};
}
function drawTrace(ctx,o,t,w,h){
 const points=o.path.map(p=>[p[0]*w,p[1]*h]);if(o.closed)points.push(points[0]);
 const lengths=points.slice(1).map((p,i)=>Math.hypot(p[0]-points[i][0],p[1]-points[i][1])),total=lengths.reduce((a,b)=>a+b,0);if(!total)return;
 const at=distance=>{let d=((distance%total)+total)%total;for(let i=0;i<lengths.length;i++){if(d<=lengths[i]&&lengths[i]){const f=d/lengths[i];return[points[i][0]+(points[i+1][0]-points[i][0])*f,points[i][1]+(points[i+1][1]-points[i][1])*f];}d-=lengths[i];}return points[0];};
 ctx.save();ctx.lineWidth=o.lineWidth;ctx.globalAlpha=o.opacity*.22;ctx.strokeStyle=o.foreground;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();
 for(let k=0;k<o.pulses;k++){const head=(t*.1+k/o.pulses)*total;for(let j=12;j>=0;j--){const p=at(head-j*Math.min(4,total/150));ctx.globalAlpha=o.opacity*(1-j/13);ctx.fillStyle=o.accent;ctx.beginPath();ctx.arc(...p,j===0?2.4:1.2,0,Math.PI*2);ctx.fill();}}
 ctx.restore();
}
function scene(o){
 let active=o.type!=='chat',started=false,epoch=performance.now(),serial=0,phase='idle',elapsed=0,previous=0;let reduced=!!o.still||matchMedia('(prefers-reduced-motion:reduce)').matches;const main=document.querySelector('main'),canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d');
 const message=(kind)=>parent.postMessage({sagaMotion:kind},'*');
 const chat=document.querySelector('.chat'),input=document.querySelector('.input'),thread=document.querySelector('.thread'),status=document.querySelector('.status');
 function reset(){started=false;phase='idle';elapsed=0;chat.hidden=true;input.textContent='';thread.replaceChildren();status.textContent='';}
 message('ready');window.addEventListener('message',e=>{if(e.source!==parent)return;if(e.data?.sagaMotion==='poster'){reduced=true;if(o.type==='terminal')document.querySelector('.feed').textContent=o.lines.join('\n');}if(e.data?.sagaMotion==='active')active=!!e.data.active;if(e.data?.sagaMotion==='reset')reset();if(e.data?.sagaMotion==='start'){reset();started=true;active=true;phase='recognize';chat.hidden=false;}});
 if(o.type==='chat'&&o.manual){const request=e=>{if(!active)return;if(e.type==='keydown'&&![' ','Enter','ArrowRight','PageDown'].includes(e.key))return;e.preventDefault();message('start-request');};document.addEventListener('click',request);document.addEventListener('keydown',request);}
 if(o.type==='chat'&&!o.manual){started=true;phase='recognize';chat.hidden=false;}
 function bubble(text,kind){const el=document.createElement('div');el.className='bubble '+kind;el.textContent=text;thread.append(el);return el;}
 let terminalElapsed=0;const terminalText=o.lines.join('\n');
 let bot;
 function tickChat(dt){if(!started||phase==='done')return;elapsed+=dt;
 if(phase==='recognize'&&elapsed>=o.recognition){phase='input';elapsed=0;}
 if(phase==='input'){input.textContent=o.user.slice(0,Math.floor(elapsed/o.typing));if(elapsed>=o.user.length*o.typing+.35){bubble(o.user,'user');input.textContent='';status.textContent='Pensando…';phase='thinking';elapsed=0;}}
 else if(phase==='thinking'&&elapsed>=o.thinking){status.textContent='';bot=bubble('','assistant');phase='answer';elapsed=0;}
 else if(phase==='answer'){bot.textContent=o.assistant.slice(0,Math.floor(elapsed/o.typing));if(elapsed>=o.assistant.length*o.typing){phase='read';elapsed=0;}}
 else if(phase==='read'&&elapsed>=o.read){phase='done';message('done');}}
 function requestLine(){serial++;const ops=['GET /silent-cloud','POST /paper-moon','PUT /silver-orbit','PATCH /soft-vector','GET /tiny-comet','DELETE /ghost-frame'];const el=document.createElement('div');el.textContent=String(serial).padStart(6,'0')+' '+ops[(serial*7+Math.floor(serial/9))%ops.length].padEnd(23,' ')+' '+(serial*2654435761>>>0).toString(16)+' '+(17+serial*37%981)+'ms 200 OK';document.querySelector('.feed').append(el);while(document.querySelector('.feed').children.length>14)document.querySelector('.feed').firstChild.remove();document.querySelector('.feed').scrollTop=1e6;}
 if(o.type==='requests'){for(let i=0;i<8;i++)requestLine();setInterval(()=>{if(active&&!document.hidden&&!reduced){requestLine();requestLine();}},Math.max(35,240/o.speed));}
 function draw(ts){requestAnimationFrame(draw);if(!active||document.hidden){previous=ts;return;}const dt=Math.min(.1,(ts-(previous||ts))/1000);previous=ts;if(o.type==='chat'){tickChat(dt);return;}if(o.type==='terminal'){terminalElapsed+=dt*o.speed;const count=reduced?terminalText.length:Math.floor(terminalElapsed/o.typing);document.querySelector('.feed').textContent=terminalText.slice(0,count)+(count<terminalText.length?'_':'');document.querySelector('.feed').scrollTop=1e6;if(count>terminalText.length+3/o.typing)terminalElapsed=0;return;}if(o.type==='requests'||(reduced&&serial))return;serial++;
 const w=main.clientWidth,h=main.clientHeight,dpr=devicePixelRatio||1;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const t=reduced?0:(ts-epoch)/1000*o.speed,r=Math.min(w*.25,h*.32),cy=h*.55;if(o.type==='hologram'){drawHologram(ctx,o,t,w,h);return;}if(o.type==='trace'){drawTrace(ctx,o,t,w,h);return;}
 function p(x,y,z){let a=t*.15+.4,xx=x*Math.cos(a)+z*Math.sin(a),zz=-x*Math.sin(a)+z*Math.cos(a),yy=y*Math.cos(.3)-zz*Math.sin(.3);const f=4/(4+zz);return[w/2+xx*r*f,cy+yy*r*f];}
 function line(v,c){ctx.beginPath();v.forEach((q,i)=>{let a=p(...q);i?ctx.lineTo(...a):ctx.moveTo(...a);});ctx.strokeStyle=c;ctx.lineWidth=.9;ctx.stroke();}
 if(o.type==='flow'){let y=h*.55,x1=w*.12,x2=w*.5,x3=w*.88;ctx.strokeStyle=o.foreground;ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(x1,y-18);ctx.bezierCurveTo(w*.35,y-18,w*.35,y,x2,y);ctx.lineTo(x3,y);ctx.moveTo(x1,y+18);ctx.bezierCurveTo(w*.35,y+18,w*.35,y,x2,y);ctx.stroke();for(const [x,yy]of[[x1,y-18],[x1,y+18],[x2,y],[x3,y]]){ctx.fillStyle=x===x3?o.accent:o.background;ctx.fillRect(x-7,yy-7,14,14);ctx.strokeRect(x-7,yy-7,14,14);}for(let j=0;j<2;j++){let n=(t*.15+j*.5)%1;ctx.fillStyle=o.secondary;ctx.beginPath();ctx.arc(x1+n*(x3-x1),y+(j?-18:18)*Math.max(0,1-n*3),2.5,0,Math.PI*2);ctx.fill();}return;}
 if(o.shape==='cube'){const v=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]];for(const [a,b]of[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]])line([v[a],v[b]],o.foreground);}
 else{for(let j=-3;j<=3;j++){let v=[],phi=j*Math.PI/9;for(let n=0;n<=60;n++){let a=n*Math.PI/30;v.push([Math.cos(phi)*Math.cos(a),Math.sin(phi),Math.cos(phi)*Math.sin(a)]);}line(v,o.foreground);}for(let j=0;j<10;j++){let v=[],a=j*Math.PI/5;for(let n=0;n<=60;n++){let phi=-Math.PI/2+n*Math.PI/60;v.push([Math.cos(phi)*Math.cos(a),Math.sin(phi),Math.cos(phi)*Math.sin(a)]);}line(v,o.foreground);}}
 let v=[];for(let n=0;n<=80;n++){let a=n*Math.PI/40;v.push([1.4*Math.cos(a),.3*Math.sin(a),.8*Math.sin(a)]);}line(v,o.secondary);const q=p(Math.cos(t*.15),0,Math.sin(t*.15));ctx.fillStyle=o.accent;ctx.fillRect(q[0]-2,q[1]-2,4,4);
 }
 requestAnimationFrame(draw);
}
// still: o deck pediu movimento nenhum (motion: none). A cena já nasce parada e completa; antes ela só sabia pela
// mensagem da página, que sob carga chegava depois de o terminal começar a digitar.
export function motionHTML(value,colors,{still=false}={}){const o={...motionOptions(value,colors),...(still?{still:true}:{})};const css=`html,body{height:100%;background:${o.type==='chat'?'transparent':o.background};color:${o.foreground};overflow:hidden}main{height:100%;position:relative}canvas{position:absolute;inset:0;width:100%;height:100%}.caption{position:absolute;top:12px;left:16px;color:${o.secondary};font:11px monospace;letter-spacing:1.5px}.feed{position:absolute;top:36px;left:16px;right:16px;bottom:12px;overflow:hidden;font:${o.type==='terminal'?o.fontSize:12}px/1.5 monospace;white-space:pre}.chat{position:absolute;inset:0;border:1px solid ${o.secondary};border-radius:16px;padding:18px;background:${o.background};display:flex;flex-direction:column;gap:12px}.chat[hidden]{display:none}.thread{flex:1;overflow:auto;display:flex;flex-direction:column;gap:12px}.bubble{font:18px/1.45 system-ui;max-width:90%;padding:10px 14px;border-radius:10px;white-space:pre-wrap}.user{align-self:flex-end;background:#263a51}.assistant{align-self:flex-start}.status{font:14px system-ui;color:${o.secondary};min-height:18px}.input{border:1px solid #51617b;border-radius:9px;min-height:48px;padding:12px;font:17px system-ui;white-space:pre-wrap}.chat-title{font:12px system-ui;letter-spacing:2px;color:${o.secondary}}`;
 const html=`<main><canvas aria-hidden="true"></canvas><div class="caption">${esc(o.type==='chat'?'':o.caption)}</div><div class="feed" aria-hidden="true"></div><section class="chat" hidden><div class="chat-title">${esc(o.caption||'ASSISTENTE')}</div><div class="thread" aria-live="polite"></div><div class="status"></div><div class="input" aria-label="Mensagem digitada"></div></section></main>`;
 const doc=playgroundDocument({html,css,javascript:`${drawHologram.toString()}\n${drawTrace.toString()}\n(${scene.toString()})(${JSON.stringify(o)});`});return `<iframe data-motion="${o.type}" data-motion-manual="${o.manual}" data-motion-finish="${o.finish}" title="${esc(o.caption||'Detalhe animado')}" sandbox="allow-scripts" style="width:100%;height:100%;border:0" srcdoc="${esc(doc)}"></iframe>`;}
